<a href="https://colab.research.google.com/github/AbdulrahmanAhmed123/AbdulrahmanAhmed123/blob/main/Data_Analyst_with_use_2_Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install requests
%pip install bs4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [ ]:
import requests

In [ ]:
requests.get('https://www.wisdompetmed.com/')

In [ ]:
response=requests.get('https://www.wisdompetmed.com/')

In [ ]:
response.url

'https://www.wisdompetmed.com/'

In [ ]:
response.status_code

200

In [ ]:
response.headers

{'Server': 'nginx', 'Date': 'Fri, 05 Jun 2026 12:54:21 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Last-Modified': 'Wed, 18 May 2022 17:53:15 GMT', 'ETag': 'W/"3239-5df4cee7de655"', 'X-Httpd-Modphp': '1', 'Host-Header': '8441280b0c35cbc1147f8ba998a563a7', 'X-Proxy-Cache': 'HIT', 'Content-Encoding': 'br'}

In [ ]:
response.content

b'<!DOCTYPE html>\n<html lang="en">\n\n<head>\n  <meta charset="UTF-8">\n  <title>Wisdom Pet Medicine</title>\n  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">\n  <link rel="stylesheet" href="css/style.css">\n  <script src="js/prefixfree.min.js"></script>\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n</head>\n\n<body>\n\n<header>\n  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">\n    <div class="container">\n      <div class="navbar-header">\n        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">\n          <span class="sr-only">Toggle navigation</span>\n          <span class="icon-bar"></span>\n          <span class="icon-bar"></span>\n          <span class="icon-bar"></span>\n        </button>\n        <a class="navbar-brand" href="#featured"><h1>Wisdom <span class="subhead">Pet Medicine</span></h1></a>\n      </div><!-- navbar-header -->\n      <div class="collapse navbar-collapse" id="collapse">\n        <ul class="nav navbar-nav navbar-right">\n          <li class="active"><a href="#featured">Home</a></li>\n          <li><a href="#mission">Mission</a></li>\n          <li><a href="#services">Services</a></li>\n          <li><a href="#staff">Staff</a></li>\n          <li><a href="#testimonials">Testimonials</a></li>\n        </ul>        \n      </div><!-- collapse navbar-collapse -->\n    </div><!-- container -->\n  </nav>\n\n  <div class="carousel fade" data-ride="carousel" id="featured">\n\n    <ol class="carousel-indicators">\n    </ol>\n\n    <div class="carousel-inner fullheight">\n      <div class="item"><img src="images/carousel-lifestyle.jpg" alt="Lifestyle Photo"></div>\n      <div class="item"><img src="images/carousel-mission.jpg" alt="Mission"></div>\n      <div class="item"><img src="images/carousel-vaccinations.jpg" alt="Vaccinations"></div>\n      <div class="item"><img src="images/carousel-parakeet.jpg" alt="Fish"></div>\n      <div class="item"><img src="images/carousel-exoticanimals.jpg" alt="Exotic Animals"></div>      \n    </div><!-- carousel-inner -->\n\n    <a class="left carousel-control" href="#featured" role="button" data-slide="prev">\n      <span class="glyphicon glyphicon-chevron-left"></span>\n    </a>\n    <a class="right carousel-control" href="#featured" role="button" data-slide="next">\n      <span class="glyphicon glyphicon-chevron-right"></span>\n    </a>\n  </div><!-- featured carousel -->\n</header>\n\n<div class="main">\n  <div class="page" id="mission">\n    <div class="content container">\n      <h2>Our Mission</h2>      \n      <div class="row">\n        <p class="col-md-5 col-md-offset-1">Wisdom Pet Medicine strives to blend the best in traditional and alternative medicine in the diagnosis and treatment of companion animals including dogs, cats, birds, reptiles, rodents, and fish. We apply the wisdom garnered in the centuries old tradition of veterinary medicine, to find the safest treatments and&nbsp;cures.</p>\n        <p class="col-md-5">We strive to be your pet\'s medical experts from youth through the senior years. We build preventative health care plans for each and every one of our patients, based on breed, age, and sex, so that your pet receives the most appropriate care at crucial milestones. We want to give your pet a long and healthy&nbsp;life.</p>\n      </div><!-- row -->\n    </div><!-- content container -->\n  </div><!-- mission page -->\n\n  <div class="page" id="services">\n    <div class="content container">\n      <h2>Services</h2>\n      <div class="row">\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-exoticpets.svg" alt="Icon">\n          <h3>Exotic Pets</h3>\n          <p>We offer specialized care for reptiles, rodents, birds, and other exotic pets.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-grooming.svg" alt="Icon">\n          <h3>Grooming</h3>\n          <p>Our therapeutic grooming treatments help battle fleas, allergic dermatitis, and other challenging skin conditions.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-health.svg" alt="Icon">\n          <h3>GeneralHealth</h3>\n          <p>Wellness and senior exams, ultrasound, x-ray, and dental cleanings are just a few of our general health services.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-nutrition.svg" alt="Icon">\n          <h3>Nutrition</h3>\n          <p>Let our nutrition experts review your pet\'s diet and prescribe a custom nutrition plan for optimum health and disease prevention.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-pestcontrol.svg" alt="Icon">\n          <h3>Pest Control</h3>\n          <p>We offer the latest advances in safe and effective prevention and treatment of fleas, ticks, worms, heart worm, and other parasites.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-vaccinations.svg" alt="Icon">\n          <h3>Vaccinations</h3>\n          <p>Our veterinarians are experienced in modern vaccination protocols that prevent many of the deadliest diseases in pets.</p>\n        </article>   \n      </div><!-- row -->   \n    </div><!-- content container -->\n  </div><!-- services page -->\n\n  <div class="page" id="staff">\n    <div class="container-fluid">\n      <h2 id="ourstaff">Our Staff</h2>\n      <div class="row">\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-winthrop.jpg" alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr. Winthrop</h3>\n              <p>Dr. Winthrop is the guardian of Missy, a three-year old Llaso mix, who he adopted at the shelter. Dr. Winthrop is passionate about spay and neuter and pet adoption, and works tireless hours outside the clinic, performing free spay and neuter surgeries for the shelter.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-chase.jpg"  alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr. Chase</h3>\n              <p>Dr. Chase spends much of her free time helping the local rescue organization find homes for animals, such as Kibbles - a Maine Coon Cat who is part of the large Chase household, including two dogs, three cats, and a turtle.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-sanders.jpg" alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr Sanders</h3>\n             <p>Leroy walked into Dr. Sanders front door when he was moving into a new house. After searching for weeks for Leroy\'s guardians, he decided to make Leroy a part of his pet family, and now has three cats.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n\n      </div><!-- outer row -->\n    </div><!-- container -->\n  </div><!-- staff page -->\n\n  <div class="page" id="testimonials">\n    <div class="container-fluid">\n      <h2>Testimonials</h2>\n      <div class="row">\n        <blockquote class="col-md-6 col-lg-3" id="janeh">\n          <div class="quote">\n            <span class="intro">During the summer, our rabbit, Tonto, began to have severe redness</span>\n            <span class="more"> and itching on his belly and feet. Through diagnostic testing, we learned that Tonto is severely allergic to over a dozens kinds of grass pollens. We\'ve now been doing allergy injections for several months, and his itching and redness have nearly gone away. I\'m very thankful to the veterinarians and staff at Wisdom for the excellent care Tonto received, and for nipping his allergies in the bud, so to speak.</span>\n            <span class="customer">Jane H.</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="mcphersons">\n          <div class="quote">\n            <span class="intro">When Samantha, our Siamese cat, began sleeping all the time</span>\n            <span class="more">and urinating excessively, we brought her to see the specialists at Wisdom. After running a blood test, Dr. Winthrop confirmed what we all feared - Samantha was showing signs of diabetes. The doctor put us on a daily routine to provide Samantha insulin injections, and showed us how to administer the shots. We weren\'t sure we could do it, but the gang at Wisdom was very supportive and encouraging. Now, two years later, Samantha is still free from any complications of diabetes, and her blood sugar regularly tests normal. Thank you, Wisdom Pet Medicine!</span>\n            <span class="customer">The McPhersons</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="johnb">\n          <div class="quote">\n            <span class="intro">The staff at Wisdom worked tirelessly to determine why our three-year old</span>\n            <span class="more">Golden Retriever, Roxie, started going into sudden kidney failure. They stabilized her and provided fluids until her kidneys were again functioning normally, but it was still a mystery as to what caused her health to decline so quickly. The vet noted our address on Roxie\'s chart, and asked if we lived on one of the orchards in the vicinity, and if Roxie had a habit of eating grapes off the vine. Our answer was "of course \xe2\x80\x93 she\'s a Retriever." That day we learned just how toxic grapes and raisins are to pets, and Roxie is no longer allowed to roam unattended in the orchard.</span>\n            <span class="customer">John B</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="lorraines">\n          <div class="quote">\n            <span class="intro">Wisdom Pet Medicine is the only clinic around that will even</span>\n            <span class="more">book pet fish for appointments. When our 13-year old Comet goldfish, McAllister, turned from silvery white to an angry red, we called around, urgently trying to find a veterinarian who could help. Wisdom not only got us in the same day, but also was able to diagnose McAllister as having a severe case of septicemia. In order to kill the harmful bacteria in his blood, we had to use a dog antibiotic in his tank every day for a week, and in the end, McAllister was good as new. I still smile upon remembering Dr. Chase pulling out an old vet school textbook to calculate the correct antibiotic dose for a fish!</span>\n            <span class="customer">Lorraine S</span>\n          </div>\n        </blockquote>          \n      </div>\n    </div><!-- container -->\n  </div><!-- testimonials page -->\n</div><!-- main -->\n\n<footer>\n  <div class="content container-fluid">\n    <div class="row">\n      <div class="col-sm-6">\n        <p>Call us toll-free at <span class="phone">888-555-1212</span></p>\n        <p>All contents &copy; 2014 <a href="http://lynda.com">Lynda.com</a>. All rights reserved.</p>    \n      </div><!-- col-sm-6 -->\n      <div class="col-sm-6">\n        <nav class="navbar navbar-default" role="navigation">\n          <ul class="nav navbar-nav navbar-right">\n            <li><a href="#">Terms of use</a></li>\n            <li><a href="#">Privacy policy</a></li>\n          </ul>\n        </nav>        \n      </div><!-- col-sm-6 -->\n    </div><!-- row -->\n  </div><!-- content container -->\n</footer>\n\n<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>\n<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>\n<script src="js/myscript.js"></script>\n</body>\n</html>\n'

In [ ]:
response.text

'<!DOCTYPE html>\n<html lang="en">\n\n<head>\n  <meta charset="UTF-8">\n  <title>Wisdom Pet Medicine</title>\n  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">\n  <link rel="stylesheet" href="css/style.css">\n  <script src="js/prefixfree.min.js"></script>\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n</head>\n\n<body>\n\n<header>\n  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">\n    <div class="container">\n      <div class="navbar-header">\n        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">\n          <span class="sr-only">Toggle navigation</span>\n          <span class="icon-bar"></span>\n          <span class="icon-bar"></span>\n          <span class="icon-bar"></span>\n        </button>\n        <a class="navbar-brand" href="#featured"><h1>Wisdom <span class="subhead">Pet Medicine</span></h1></a>\n      </div><!-- navbar-header -->\n      <div class="collapse navbar-collapse" id="collapse">\n        <ul class="nav navbar-nav navbar-right">\n          <li class="active"><a href="#featured">Home</a></li>\n          <li><a href="#mission">Mission</a></li>\n          <li><a href="#services">Services</a></li>\n          <li><a href="#staff">Staff</a></li>\n          <li><a href="#testimonials">Testimonials</a></li>\n        </ul>        \n      </div><!-- collapse navbar-collapse -->\n    </div><!-- container -->\n  </nav>\n\n  <div class="carousel fade" data-ride="carousel" id="featured">\n\n    <ol class="carousel-indicators">\n    </ol>\n\n    <div class="carousel-inner fullheight">\n      <div class="item"><img src="images/carousel-lifestyle.jpg" alt="Lifestyle Photo"></div>\n      <div class="item"><img src="images/carousel-mission.jpg" alt="Mission"></div>\n      <div class="item"><img src="images/carousel-vaccinations.jpg" alt="Vaccinations"></div>\n      <div class="item"><img src="images/carousel-parakeet.jpg" alt="Fish"></div>\n      <div class="item"><img src="images/carousel-exoticanimals.jpg" alt="Exotic Animals"></div>      \n    </div><!-- carousel-inner -->\n\n    <a class="left carousel-control" href="#featured" role="button" data-slide="prev">\n      <span class="glyphicon glyphicon-chevron-left"></span>\n    </a>\n    <a class="right carousel-control" href="#featured" role="button" data-slide="next">\n      <span class="glyphicon glyphicon-chevron-right"></span>\n    </a>\n  </div><!-- featured carousel -->\n</header>\n\n<div class="main">\n  <div class="page" id="mission">\n    <div class="content container">\n      <h2>Our Mission</h2>      \n      <div class="row">\n        <p class="col-md-5 col-md-offset-1">Wisdom Pet Medicine strives to blend the best in traditional and alternative medicine in the diagnosis and treatment of companion animals including dogs, cats, birds, reptiles, rodents, and fish. We apply the wisdom garnered in the centuries old tradition of veterinary medicine, to find the safest treatments and&nbsp;cures.</p>\n        <p class="col-md-5">We strive to be your pet\'s medical experts from youth through the senior years. We build preventative health care plans for each and every one of our patients, based on breed, age, and sex, so that your pet receives the most appropriate care at crucial milestones. We want to give your pet a long and healthy&nbsp;life.</p>\n      </div><!-- row -->\n    </div><!-- content container -->\n  </div><!-- mission page -->\n\n  <div class="page" id="services">\n    <div class="content container">\n      <h2>Services</h2>\n      <div class="row">\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-exoticpets.svg" alt="Icon">\n          <h3>Exotic Pets</h3>\n          <p>We offer specialized care for reptiles, rodents, birds, and other exotic pets.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-grooming.svg" alt="Icon">\n          <h3>Grooming</h3>\n          <p>Our therapeutic grooming treatments help battle fleas, allergic dermatitis, and other challenging skin conditions.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-health.svg" alt="Icon">\n          <h3>GeneralHealth</h3>\n          <p>Wellness and senior exams, ultrasound, x-ray, and dental cleanings are just a few of our general health services.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-nutrition.svg" alt="Icon">\n          <h3>Nutrition</h3>\n          <p>Let our nutrition experts review your pet\'s diet and prescribe a custom nutrition plan for optimum health and disease prevention.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-pestcontrol.svg" alt="Icon">\n          <h3>Pest Control</h3>\n          <p>We offer the latest advances in safe and effective prevention and treatment of fleas, ticks, worms, heart worm, and other parasites.</p>\n        </article>\n\n        <article class="service col-md-4 col-sm-6 col-xs-12">\n          <img class="icon" src="images/icon-vaccinations.svg" alt="Icon">\n          <h3>Vaccinations</h3>\n          <p>Our veterinarians are experienced in modern vaccination protocols that prevent many of the deadliest diseases in pets.</p>\n        </article>   \n      </div><!-- row -->   \n    </div><!-- content container -->\n  </div><!-- services page -->\n\n  <div class="page" id="staff">\n    <div class="container-fluid">\n      <h2 id="ourstaff">Our Staff</h2>\n      <div class="row">\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-winthrop.jpg" alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr. Winthrop</h3>\n              <p>Dr. Winthrop is the guardian of Missy, a three-year old Llaso mix, who he adopted at the shelter. Dr. Winthrop is passionate about spay and neuter and pet adoption, and works tireless hours outside the clinic, performing free spay and neuter surgeries for the shelter.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-chase.jpg"  alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr. Chase</h3>\n              <p>Dr. Chase spends much of her free time helping the local rescue organization find homes for animals, such as Kibbles - a Maine Coon Cat who is part of the large Chase household, including two dogs, three cats, and a turtle.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n        <div class="doctor col-lg-4">\n          <div class="row">\n            <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">\n              <img class="img-circle" src="images/doctor-sanders.jpg" alt="Photo of Dr Sanders">\n            </div><!-- photo -->\n            <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">\n              <h3>Dr Sanders</h3>\n             <p>Leroy walked into Dr. Sanders front door when he was moving into a new house. After searching for weeks for Leroy\'s guardians, he decided to make Leroy a part of his pet family, and now has three cats.</p>\n            </div><!-- info -->\n          </div> <!-- inner row -->\n        </div> <!-- doctor -->\n\n\n      </div><!-- outer row -->\n    </div><!-- container -->\n  </div><!-- staff page -->\n\n  <div class="page" id="testimonials">\n    <div class="container-fluid">\n      <h2>Testimonials</h2>\n      <div class="row">\n        <blockquote class="col-md-6 col-lg-3" id="janeh">\n          <div class="quote">\n            <span class="intro">During the summer, our rabbit, Tonto, began to have severe redness</span>\n            <span class="more"> and itching on his belly and feet. Through diagnostic testing, we learned that Tonto is severely allergic to over a dozens kinds of grass pollens. We\'ve now been doing allergy injections for several months, and his itching and redness have nearly gone away. I\'m very thankful to the veterinarians and staff at Wisdom for the excellent care Tonto received, and for nipping his allergies in the bud, so to speak.</span>\n            <span class="customer">Jane H.</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="mcphersons">\n          <div class="quote">\n            <span class="intro">When Samantha, our Siamese cat, began sleeping all the time</span>\n            <span class="more">and urinating excessively, we brought her to see the specialists at Wisdom. After running a blood test, Dr. Winthrop confirmed what we all feared - Samantha was showing signs of diabetes. The doctor put us on a daily routine to provide Samantha insulin injections, and showed us how to administer the shots. We weren\'t sure we could do it, but the gang at Wisdom was very supportive and encouraging. Now, two years later, Samantha is still free from any complications of diabetes, and her blood sugar regularly tests normal. Thank you, Wisdom Pet Medicine!</span>\n            <span class="customer">The McPhersons</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="johnb">\n          <div class="quote">\n            <span class="intro">The staff at Wisdom worked tirelessly to determine why our three-year old</span>\n            <span class="more">Golden Retriever, Roxie, started going into sudden kidney failure. They stabilized her and provided fluids until her kidneys were again functioning normally, but it was still a mystery as to what caused her health to decline so quickly. The vet noted our address on Roxie\'s chart, and asked if we lived on one of the orchards in the vicinity, and if Roxie had a habit of eating grapes off the vine. Our answer was "of course â\x80\x93 she\'s a Retriever." That day we learned just how toxic grapes and raisins are to pets, and Roxie is no longer allowed to roam unattended in the orchard.</span>\n            <span class="customer">John B</span>\n          </div>\n        </blockquote>\n\n        <blockquote class="col-md-6 col-lg-3" id="lorraines">\n          <div class="quote">\n            <span class="intro">Wisdom Pet Medicine is the only clinic around that will even</span>\n            <span class="more">book pet fish for appointments. When our 13-year old Comet goldfish, McAllister, turned from silvery white to an angry red, we called around, urgently trying to find a veterinarian who could help. Wisdom not only got us in the same day, but also was able to diagnose McAllister as having a severe case of septicemia. In order to kill the harmful bacteria in his blood, we had to use a dog antibiotic in his tank every day for a week, and in the end, McAllister was good as new. I still smile upon remembering Dr. Chase pulling out an old vet school textbook to calculate the correct antibiotic dose for a fish!</span>\n            <span class="customer">Lorraine S</span>\n          </div>\n        </blockquote>          \n      </div>\n    </div><!-- container -->\n  </div><!-- testimonials page -->\n</div><!-- main -->\n\n<footer>\n  <div class="content container-fluid">\n    <div class="row">\n      <div class="col-sm-6">\n        <p>Call us toll-free at <span class="phone">888-555-1212</span></p>\n        <p>All contents &copy; 2014 <a href="http://lynda.com">Lynda.com</a>. All rights reserved.</p>    \n      </div><!-- col-sm-6 -->\n      <div class="col-sm-6">\n        <nav class="navbar navbar-default" role="navigation">\n          <ul class="nav navbar-nav navbar-right">\n            <li><a href="#">Terms of use</a></li>\n            <li><a href="#">Privacy policy</a></li>\n          </ul>\n        </nav>        \n      </div><!-- col-sm-6 -->\n    </div><!-- row -->\n  </div><!-- content container -->\n</footer>\n\n<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>\n<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>\n<script src="js/myscript.js"></script>\n</body>\n</html>\n'

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup=BeautifulSoup(response.text)

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Wisdom Pet Medicine
  </title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="css/style.css" rel="stylesheet"/>
  <script src="js/prefixfree.min.js">
  </script>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
 </head>
 <body>
  <header>
   <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
     <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#collapse" data-toggle="collapse" type="button">
       <span class="sr-only">
        Toggle navigation
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
      </button>
      <a class="navbar-brand" href="#featured">
       <h1>
        Wisdom
        <span class="subhead">
         Pet Medicine
        </span>
       </h1>
      </a>
     </div>
     <!-- navbar-header -->
     <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav navbar-right">
       <li class="active">
        <a href="#featured">
         Home
        </a>
       </li>
       <li>
        <a href="#mission">
         Mission
        </a>
       </li>
       <li>
        <a href="#services">
         Services
        </a>
       </li>
       <li>
        <a href="#staff">
         Staff
        </a>
       </li>
       <li>
        <a href="#testimonials">
         Testimonials
        </a>
       </li>
      </ul>
     </div>
     <!-- collapse navbar-collapse -->
    </div>
    <!-- container -->
   </nav>
   <div class="carousel fade" data-ride="carousel" id="featured">
    <ol class="carousel-indicators">
    </ol>
    <div class="carousel-inner fullheight">
     <div class="item">
      <img alt="Lifestyle Photo" src="images/carousel-lifestyle.jpg"/>
     </div>
     <div class="item">
      <img alt="Mission" src="images/carousel-mission.jpg"/>
     </div>
     <div class="item">
      <img alt="Vaccinations" src="images/carousel-vaccinations.jpg"/>
     </div>
     <div class="item">
      <img alt="Fish" src="images/carousel-parakeet.jpg"/>
     </div>
     <div class="item">
      <img alt="Exotic Animals" src="images/carousel-exoticanimals.jpg"/>
     </div>
    </div>
    <!-- carousel-inner -->
    <a class="left carousel-control" data-slide="prev" href="#featured" role="button">
     <span class="glyphicon glyphicon-chevron-left">
     </span>
    </a>
    <a class="right carousel-control" data-slide="next" href="#featured" role="button">
     <span class="glyphicon glyphicon-chevron-right">
     </span>
    </a>
   </div>
   <!-- featured carousel -->
  </header>
  <div class="main">
   <div class="page" id="mission">
    <div class="content container">
     <h2>
      Our Mission
     </h2>
     <div class="row">
      <p class="col-md-5 col-md-offset-1">
       Wisdom Pet Medicine strives to blend the best in traditional and alternative medicine in the diagnosis and treatment of companion animals including dogs, cats, birds, reptiles, rodents, and fish. We apply the wisdom garnered in the centuries old tradition of veterinary medicine, to find the safest treatments and cures.
      </p>
      <p class="col-md-5">
       We strive to be your pet's medical experts from youth through the senior years. We build preventative health care plans for each and every one of our patients, based on breed, age, and sex, so that your pet receives the most appropriate care at crucial milestones. We want to give your pet a long and healthy life.
      </p>
     </div>
     <!-- row -->
    </div>
    <!-- content container -->
   </div>
   <!-- mission page -->
   <div class="page" id="services">
    <div class="content container">
     <h2>
      Services
     </h2>
     <div class="row">
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-exoticpets.svg"/>
       <h3>
        Exotic Pets
       </h3>
       <p>
        We offer specialized care for reptiles, rodents, birds, and other exotic pets.
       </p>
      </article>
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-grooming.svg"/>
       <h3>
        Grooming
       </h3>
       <p>
        Our therapeutic grooming treatments help battle fleas, allergic dermatitis, and other challenging skin conditions.
       </p>
      </article>
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-health.svg"/>
       <h3>
        GeneralHealth
       </h3>
       <p>
        Wellness and senior exams, ultrasound, x-ray, and dental cleanings are just a few of our general health services.
       </p>
      </article>
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-nutrition.svg"/>
       <h3>
        Nutrition
       </h3>
       <p>
        Let our nutrition experts review your pet's diet and prescribe a custom nutrition plan for optimum health and disease prevention.
       </p>
      </article>
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-pestcontrol.svg"/>
       <h3>
        Pest Control
       </h3>
       <p>
        We offer the latest advances in safe and effective prevention and treatment of fleas, ticks, worms, heart worm, and other parasites.
       </p>
      </article>
      <article class="service col-md-4 col-sm-6 col-xs-12">
       <img alt="Icon" class="icon" src="images/icon-vaccinations.svg"/>
       <h3>
        Vaccinations
       </h3>
       <p>
        Our veterinarians are experienced in modern vaccination protocols that prevent many of the deadliest diseases in pets.
       </p>
      </article>
     </div>
     <!-- row -->
    </div>
    <!-- content container -->
   </div>
   <!-- services page -->
   <div class="page" id="staff">
    <div class="container-fluid">
     <h2 id="ourstaff">
      Our Staff
     </h2>
     <div class="row">
      <div class="doctor col-lg-4">
       <div class="row">
        <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">
         <img alt="Photo of Dr Sanders" class="img-circle" src="images/doctor-winthrop.jpg"/>
        </div>
        <!-- photo -->
        <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">
         <h3>
          Dr. Winthrop
         </h3>
         <p>
          Dr. Winthrop is the guardian of Missy, a three-year old Llaso mix, who he adopted at the shelter. Dr. Winthrop is passionate about spay and neuter and pet adoption, and works tireless hours outside the clinic, performing free spay and neuter surgeries for the shelter.
         </p>
        </div>
        <!-- info -->
       </div>
       <!-- inner row -->
      </div>
      <!-- doctor -->
      <div class="doctor col-lg-4">
       <div class="row">
        <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">
         <img alt="Photo of Dr Sanders" class="img-circle" src="images/doctor-chase.jpg"/>
        </div>
        <!-- photo -->
        <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">
         <h3>
          Dr. Chase
         </h3>
         <p>
          Dr. Chase spends much of her free time helping the local rescue organization find homes for animals, such as Kibbles - a Maine Coon Cat who is part of the large Chase household, including two dogs, three cats, and a turtle.
         </p>
        </div>
        <!-- info -->
       </div>
       <!-- inner row -->
      </div>
      <!-- doctor -->
      <div class="doctor col-lg-4">
       <div class="row">
        <div class="photo col-xs-6 col-xs-offset-3 col-sm-3 col-sm-offset-1 col-md-2 col-md-offset-2 col-lg-4 col-lg-offset-0">
         <img alt="Photo of Dr Sanders" class="img-circle" src="images/doctor-sanders.jpg"/>
        </div>
        <!-- photo -->
        <div class="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8">
         <h3>
          Dr Sanders
         </h3>
         <p>
          Leroy walked into Dr. Sanders front door when he was moving into a new house. After searching for weeks for Leroy's guardians, he decided to make Leroy a part of his pet family, and now has three cats.
         </p>
        </div>
        <!-- info -->
       </div>
       <!-- inner row -->
      </div>
      <!-- doctor -->
     </div>
     <!-- outer row -->
    </div>
    <!-- container -->
   </div>
   <!-- staff page -->
   <div class="page" id="testimonials">
    <div class="container-fluid">
     <h2>
      Testimonials
     </h2>
     <div class="row">
      <blockquote class="col-md-6 col-lg-3" id="janeh">
       <div class="quote">
        <span class="intro">
         During the summer, our rabbit, Tonto, began to have severe redness
        </span>
        <span class="more">
         and itching on his belly and feet. Through diagnostic testing, we learned that Tonto is severely allergic to over a dozens kinds of grass pollens. We've now been doing allergy injections for several months, and his itching and redness have nearly gone away. I'm very thankful to the veterinarians and staff at Wisdom for the excellent care Tonto received, and for nipping his allergies in the bud, so to speak.
        </span>
        <span class="customer">
         Jane H.
        </span>
       </div>
      </blockquote>
      <blockquote class="col-md-6 col-lg-3" id="mcphersons">
       <div class="quote">
        <span class="intro">
         When Samantha, our Siamese cat, began sleeping all the time
        </span>
        <span class="more">
         and urinating excessively, we brought her to see the specialists at Wisdom. After running a blood test, Dr. Winthrop confirmed what we all feared - Samantha was showing signs of diabetes. The doctor put us on a daily routine to provide Samantha insulin injections, and showed us how to administer the shots. We weren't sure we could do it, but the gang at Wisdom was very supportive and encouraging. Now, two years later, Samantha is still free from any complications of diabetes, and her blood sugar regularly tests normal. Thank you, Wisdom Pet Medicine!
        </span>
        <span class="customer">
         The McPhersons
        </span>
       </div>
      </blockquote>
      <blockquote class="col-md-6 col-lg-3" id="johnb">
       <div class="quote">
        <span class="intro">
         The staff at Wisdom worked tirelessly to determine why our three-year old
        </span>
        <span class="more">
         Golden Retriever, Roxie, started going into sudden kidney failure. They stabilized her and provided fluids until her kidneys were again functioning normally, but it was still a mystery as to what caused her health to decline so quickly. The vet noted our address on Roxie's chart, and asked if we lived on one of the orchards in the vicinity, and if Roxie had a habit of eating grapes off the vine. Our answer was "of course â she's a Retriever." That day we learned just how toxic grapes and raisins are to pets, and Roxie is no longer allowed to roam unattended in the orchard.
        </span>
        <span class="customer">
         John B
        </span>
       </div>
      </blockquote>
      <blockquote class="col-md-6 col-lg-3" id="lorraines">
       <div class="quote">
        <span class="intro">
         Wisdom Pet Medicine is the only clinic around that will even
        </span>
        <span class="more">
         book pet fish for appointments. When our 13-year old Comet goldfish, McAllister, turned from silvery white to an angry red, we called around, urgently trying to find a veterinarian who could help. Wisdom not only got us in the same day, but also was able to diagnose McAllister as having a severe case of septicemia. In order to kill the harmful bacteria in his blood, we had to use a dog antibiotic in his tank every day for a week, and in the end, McAllister was good as new. I still smile upon remembering Dr. Chase pulling out an old vet school textbook to calculate the correct antibiotic dose for a fish!
        </span>
        <span class="customer">
         Lorraine S
        </span>
       </div>
      </blockquote>
     </div>
    </div>
    <!-- container -->
   </div>
   <!-- testimonials page -->
  </div>
  <!-- main -->
  <footer>
   <div class="content container-fluid">
    <div class="row">
     <div class="col-sm-6">
      <p>
       Call us toll-free at
       <span class="phone">
        888-555-1212
       </span>
      </p>
      <p>
       All contents © 2014
       <a href="http://lynda.com">
        Lynda.com
       </a>
       . All rights reserved.
      </p>
     </div>
     <!-- col-sm-6 -->
     <div class="col-sm-6">
      <nav class="navbar navbar-default" role="navigation">
       <ul class="nav navbar-nav navbar-right">
        <li>
         <a href="#">
          Terms of use
         </a>
        </li>
        <li>
         <a href="#">
          Privacy policy
         </a>
        </li>
       </ul>
      </nav>
     </div>
     <!-- col-sm-6 -->
    </div>
    <!-- row -->
   </div>
   <!-- content container -->
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js">
  </script>
  <script src="js/myscript.js">
  </script>
 </body>
</html>

In [ ]:
print(soup.find('title').text)

Wisdom Pet Medicine

In [ ]:
print(soup.find_all('article'))

[<article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-exoticpets.svg"/>
<h3>Exotic Pets</h3>
<p>We offer specialized care for reptiles, rodents, birds, and other exotic pets.</p>
</article>, <article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-grooming.svg"/>
<h3>Grooming</h3>
<p>Our therapeutic grooming treatments help battle fleas, allergic dermatitis, and other challenging skin conditions.</p>
</article>, <article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-health.svg"/>
<h3>GeneralHealth</h3>
<p>Wellness and senior exams, ultrasound, x-ray, and dental cleanings are just a few of our general health services.</p>
</article>, <article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-nutrition.svg"/>
<h3>Nutrition</h3>
<p>Let our nutrition experts review your pet's diet and prescribe a custom nutrition plan for optimum health and disease prevention.</p>
</article>, <article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-pestcontrol.svg"/>
<h3>Pest Control</h3>
<p>We offer the latest advances in safe and effective prevention and treatment of fleas, ticks, worms, heart worm, and other parasites.</p>
</article>, <article class="service col-md-4 col-sm-6 col-xs-12">
<img alt="Icon" class="icon" src="images/icon-vaccinations.svg"/>
<h3>Vaccinations</h3>
<p>Our veterinarians are experienced in modern vaccination protocols that prevent many of the deadliest diseases in pets.</p>
</article>]

In [ ]:
print(soup.find("span",class_='phone').text)

888-555-1212

In [ ]:
Features_testimonials=soup.find_all("div",class_="quote")
for testimonial in Features_testimonials:
    print(testimonial.text)

During the summer, our rabbit, Tonto, began to have severe redness
 and itching on his belly and feet. Through diagnostic testing, we learned that Tonto is severely allergic to over a dozens kinds of grass pollens. We've now been doing allergy injections for several months, and his itching and redness have nearly gone away. I'm very thankful to the veterinarians and staff at Wisdom for the excellent care Tonto received, and for nipping his allergies in the bud, so to speak.
Jane H.


When Samantha, our Siamese cat, began sleeping all the time
and urinating excessively, we brought her to see the specialists at Wisdom. After running a blood test, Dr. Winthrop confirmed what we all feared - Samantha was showing signs of diabetes. The doctor put us on a daily routine to provide Samantha insulin injections, and showed us how to administer the shots. We weren't sure we could do it, but the gang at Wisdom was very supportive and encouraging. Now, two years later, Samantha is still free from any complications of diabetes, and her blood sugar regularly tests normal. Thank you, Wisdom Pet Medicine!
The McPhersons


The staff at Wisdom worked tirelessly to determine why our three-year old
Golden Retriever, Roxie, started going into sudden kidney failure. They stabilized her and provided fluids until her kidneys were again functioning normally, but it was still a mystery as to what caused her health to decline so quickly. The vet noted our address on Roxie's chart, and asked if we lived on one of the orchards in the vicinity, and if Roxie had a habit of eating grapes off the vine. Our answer was "of course â she's a Retriever." That day we learned just how toxic grapes and raisins are to pets, and Roxie is no longer allowed to roam unattended in the orchard.
John B


Wisdom Pet Medicine is the only clinic around that will even
book pet fish for appointments. When our 13-year old Comet goldfish, McAllister, turned from silvery white to an angry red, we called around, urgently trying to find a veterinarian who could help. Wisdom not only got us in the same day, but also was able to diagnose McAllister as having a severe case of septicemia. In order to kill the harmful bacteria in his blood, we had to use a dog antibiotic in his tank every day for a week, and in the end, McAllister was good as new. I still smile upon remembering Dr. Chase pulling out an old vet school textbook to calculate the correct antibiotic dose for a fish!
Lorraine S

In [ ]:
staffMember=soup.find_all("div",class_="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8")
for staff in staffMember:
    print(staff.text)

Dr. Winthrop
Dr. Winthrop is the guardian of Missy, a three-year old Llaso mix, who he adopted at the shelter. Dr. Winthrop is passionate about spay and neuter and pet adoption, and works tireless hours outside the clinic, performing free spay and neuter surgeries for the shelter.


Dr. Chase
Dr. Chase spends much of her free time helping the local rescue organization find homes for animals, such as Kibbles - a Maine Coon Cat who is part of the large Chase household, including two dogs, three cats, and a turtle.


Dr Sanders
Leroy walked into Dr. Sanders front door when he was moving into a new house. After searching for weeks for Leroy's guardians, he decided to make Leroy a part of his pet family, and now has three cats.

In [ ]:
links=soup.find_all("a")
for link in links:
    print(link.text,link.get("href"))

Wisdom Pet Medicine #featured
Home #featured
Mission #mission
Services #services
Staff #staff
Testimonials #testimonials


 #featured


 #featured
Lynda.com http://lynda.com
Terms of use #
Privacy policy #

In [ ]:
with open("wisdompetMedicie","w") as f:
  f.write(soup.prettify())

In [ ]:
  with open("alphaAPI.txt","w") as f:
   f.write("45AZUUKMZXNB674Q")

In [ ]:
with open("alphaAPI.txt") as f:
  api=f.read().strip()
print(api)

45AZUUKMZXNB674Q

In [ ]:
%pip install alpha_vantage

Collecting alpha_vantage
  Downloading alpha_vantage-3.0.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from alpha_vantage) (3.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from alpha_vantage) (2.32.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->alpha_vantage) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->alpha_vantage) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->alpha_vantage) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->alpha_vantage) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->alpha_vantage) (2026.5.20)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->alpha_vantage) (4.15.0)
Downloading alpha_vantage-3.0.0-py3-none-any.whl (35 kB)
Installing collected packages: alpha_vantage
Successfully installed alpha_vantage-3.0.0

In [ ]:
import pandas as pd
import io
import requests
from alpha_vantage.timeseries import TimeSeries
from bs4 import BeautifulSoup

In [ ]:
ts1=TimeSeries(key=api)
print(ts1)

<alpha_vantage.timeseries.TimeSeries object at 0x7de62b5c5c40>

In [ ]:
ts1.get_monthly("AApl")

({'2026-06-04': {'1. open': '309.6250',
   '2. high': '316.9400',
   '3. low': '305.0200',
   '4. close': '311.2300',
   '5. volume': '189090488'},
  '2026-05-29': {'1. open': '278.8550',
   '2. high': '315.0000',
   '3. low': '274.8601',
   '4. close': '312.0600',
   '5. volume': '980364419'},
  '2026-04-30': {'1. open': '254.0800',
   '2. high': '276.0000',
   '3. low': '245.7000',
   '4. close': '271.3500',
   '5. volume': '907538475'},
  '2026-03-31': {'1. open': '262.4100',
   '2. high': '266.5300',
   '3. low': '245.5100',
   '4. close': '253.7900',
   '5. volume': '900035757'},
  '2026-02-27': {'1. open': '260.0300',
   '2. high': '280.9050',
   '3. low': '255.4500',
   '4. close': '264.1800',
   '5. volume': '988325816'},
  '2026-01-30': {'1. open': '272.2550',
   '2. high': '277.8400',
   '3. low': '243.4200',
   '4. close': '259.4800',
   '5. volume': '1036170325'},
  '2025-12-31': {'1. open': '278.0100',
   '2. high': '288.6200',
   '3. low': '266.9500',
   '4. close': '271.8600',
   '5. volume': '922283649'},
  '2025-11-28': {'1. open': '270.4200',
   '2. high': '280.3800',
   '3. low': '265.3200',
   '4. close': '278.8500',
   '5. volume': '876481453'},
  '2025-10-31': {'1. open': '255.0400',
   '2. high': '277.3200',
   '3. low': '244.0000',
   '4. close': '270.3700',
   '5. volume': '1097142365'},
  '2025-09-30': {'1. open': '229.2500',
   '2. high': '257.6000',
   '3. low': '225.9500',
   '4. close': '254.6300',
   '5. volume': '1265170319'},
  '2025-08-29': {'1. open': '210.8650',
   '2. high': '235.1200',
   '3. low': '201.5000',
   '4. close': '232.1400',
   '5. volume': '1218125232'},
  '2025-07-31': {'1. open': '206.6650',
   '2. high': '216.2300',
   '3. low': '206.1401',
   '4. close': '207.5700',
   '5. volume': '1079935847'},
  '2025-06-30': {'1. open': '200.2800',
   '2. high': '207.3900',
   '3. low': '195.0700',
   '4. close': '205.1700',
   '5. volume': '1100504397'},
  '2025-05-30': {'1. open': '209.0800',
   '2. high': '214.5600',
   '3. low': '193.2500',
   '4. close': '200.8500',
   '5. volume': '1195889556'},
  '2025-04-30': {'1. open': '219.8050',
   '2. high': '225.1900',
   '3. low': '169.2101',
   '4. close': '212.5000',
   '5. volume': '1607318483'},
  '2025-03-31': {'1. open': '241.7900',
   '2. high': '244.0272',
   '3. low': '208.4200',
   '4. close': '222.1300',
   '5. volume': '1114686136'},
  '2025-02-28': {'1. open': '229.9900',
   '2. high': '250.0000',
   '3. low': '225.7000',
   '4. close': '241.8400',
   '5. volume': '862317019'},
  '2025-01-31': {'1. open': '248.9300',
   '2. high': '249.1000',
   '3. low': '219.3800',
   '4. close': '236.0000',
   '5. volume': '1200291603'},
  '2024-12-31': {'1. open': '237.2700',
   '2. high': '260.1000',
   '3. low': '237.1600',
   '4. close': '250.4200',
   '5. volume': '977942014'},
  '2024-11-29': {'1. open': '220.9650',
   '2. high': '237.8100',
   '3. low': '219.7100',
   '4. close': '237.3300',
   '5. volume': '891640714'},
  '2024-10-31': {'1. open': '229.5200',
   '2. high': '237.4900',
   '3. low': '221.3300',
   '4. close': '225.9100',
   '5. volume': '930835961'},
  '2024-09-30': {'1. open': '228.5500',
   '2. high': '233.0900',
   '3. low': '213.9200',
   '4. close': '233.0000',
   '5. volume': '1231814423'},
  '2024-08-30': {'1. open': '224.3700',
   '2. high': '232.9200',
   '3. low': '196.0000',
   '4. close': '229.0000',
   '5. volume': '1122666993'},
  '2024-07-31': {'1. open': '212.0900',
   '2. high': '237.2300',
   '3. low': '211.9200',
   '4. close': '222.0800',
   '5. volume': '1153193377'},
  '2024-06-28': {'1. open': '192.9000',
   '2. high': '220.2000',
   '3. low': '192.1500',
   '4. close': '210.6200',
   '5. volume': '1723984420'},
  '2024-05-31': {'1. open': '169.5800',
   '2. high': '193.0000',
   '3. low': '169.1100',
   '4. close': '192.2500',
   '5. volume': '1336570142'},
  '2024-04-30': {'1. open': '171.1900',
   '2. high': '178.3600',
   '3. low': '164.0750',
   '4. close': '170.3300',
   '5. volume': '1240410671'},
  '2024-03-28': {'1. open': '179.5500',
   '2. high': '180.5300',
   '3. low': '168.4900',
   '4. close': '171.4800',
   '5. volume': '1430780147'},
  '2024-02-29': {'1. open': '183.9850',
   '2. high': '191.0500',
   '3. low': '179.2500',
   '4. close': '180.7500',
   '5. volume': '1161711745'},
  '2024-01-31': {'1. open': '187.1500',
   '2. high': '196.3800',
   '3. low': '180.1700',
   '4. close': '184.4000',
   '5. volume': '1187139861'},
  '2023-12-29': {'1. open': '190.3300',
   '2. high': '199.6200',
   '3. low': '187.4511',
   '4. close': '192.5300',
   '5. volume': '1062317718'},
  '2023-11-30': {'1. open': '171.0000',
   '2. high': '192.9300',
   '3. low': '170.1200',
   '4. close': '189.9500',
   '5. volume': '1099760711'},
  '2023-10-31': {'1. open': '171.2200',
   '2. high': '182.3400',
   '3. low': '165.6700',
   '4. close': '170.7700',
   '5. volume': '1172845791'},
  '2023-09-29': {'1. open': '189.4850',
   '2. high': '189.9800',
   '3. low': '167.6200',
   '4. close': '171.2100',
   '5. volume': '1337873796'},
  '2023-08-31': {'1. open': '196.2350',
   '2. high': '196.7300',
   '3. low': '171.9600',
   '4. close': '187.8700',
   '5. volume': '1323817340'},
  '2023-07-31': {'1. open': '193.7800',
   '2. high': '198.2300',
   '3. low': '186.6000',
   '4. close': '196.4500',
   '5. volume': '996368613'},
  '2023-06-30': {'1. open': '177.7000',
   '2. high': '194.4800',
   '3. low': '176.9306',
   '4. close': '193.9700',
   '5. volume': '1297863403'},
  '2023-05-31': {'1. open': '169.2800',
   '2. high': '179.3500',
   '3. low': '164.3100',
   '4. close': '177.2500',
   '5. volume': '1275052503'},
  '2023-04-28': {'1. open': '164.2700',
   '2. high': '169.8500',
   '3. low': '159.7800',
   '4. close': '169.6800',
   '5. volume': '967580718'},
  '2023-03-31': {'1. open': '146.8300',
   '2. high': '165.0000',
   '3. low': '143.9000',
   '4. close': '164.9000',
   '5. volume': '1520461315'},
  '2023-02-28': {'1. open': '143.9700',
   '2. high': '157.3800',
   '3. low': '141.3200',
   '4. close': '147.4100',
   '5. volume': '1307294493'},
  '2023-01-31': {'1. open': '130.2800',
   '2. high': '147.2300',
   '3. low': '124.1700',
   '4. close': '144.2900',
   '5. volume': '1443652725'},
  '2022-12-30': {'1. open': '148.2100',
   '2. high': '150.9199',
   '3. low': '125.8700',
   '4. close': '129.9300',
   '5. volume': '1675731304'},
  '2022-11-30': {'1. open': '155.0800',
   '2. high': '155.4500',
   '3. low': '134.3800',
   '4. close': '148.0300',
   '5. volume': '1724948219'},
  '2022-10-31': {'1. open': '138.2100',
   '2. high': '157.5000',
   '3. low': '134.3700',
   '4. close': '153.3400',
   '5. volume': '1868381344'},
  '2022-09-30': {'1. open': '156.6400',
   '2. high': '164.2600',
   '3. low': '138.0000',
   '4. close': '138.2000',
   '5. volume': '2083968147'},
  '2022-08-31': {'1. open': '161.0100',
   '2. high': '176.1500',
   '3. low': '157.1400',
   '4. close': '157.2200',
   '5. volume': '1509735435'},
  '2022-07-29': {'1. open': '136.0400',
   '2. high': '163.6300',
   '3. low': '135.6600',
   '4. close': '162.5100',
   '5. volume': '1447364668'},
  '2022-06-30': {'1. open': '149.9000',
   '2. high': '151.7400',
   '3. low': '129.0400',
   '4. close': '136.7200',
   '5. volume': '1749297959'},
  '2022-05-31': {'1. open': '156.7100',
   '2. high': '166.4800',
   '3. low': '132.6100',
   '4. close': '148.8400',
   '5. volume': '2400305601'},
  '2022-04-29': {'1. open': '174.0300',
   '2. high': '178.4900',
   '3. low': '155.3800',
   '4. close': '157.6500',
   '5. volume': '1683547838'},
  '2022-03-31': {'1. open': '164.6950',
   '2. high': '179.6100',
   '3. low': '150.1000',
   '4. close': '174.6100',
   '5. volume': '2171827429'},
  '2022-02-28': {'1. open': '174.0100',
   '2. high': '176.6500',
   '3. low': '152.0000',
   '4. close': '165.1200',
   '5. volume': '1628570227'},
  '2022-01-31': {'1. open': '177.8300',
   '2. high': '182.9400',
   '3. low': '154.7000',
   '4. close': '174.7800',
   '5. volume': '2106513962'},
  '2021-12-31': {'1. open': '167.4800',
   '2. high': '182.1300',
   '3. low': '157.8000',
   '4. close': '177.5700',
   '5. volume': '2443227128'},
  '2021-11-30': {'1. open': '148.9850',
   '2. high': '165.7000',
   '3. low': '147.4800',
   '4. close': '165.3000',
   '5. volume': '1688864233'},
  '2021-10-29': {'1. open': '141.9000',
   '2. high': '153.1650',
   '3. low': '138.2700',
   '4. close': '149.8000',
   '5. volume': '1565079040'},
  '2021-09-30': {'1. open': '152.8300',
   '2. high': '157.2600',
   '3. low': '141.2700',
   '4. close': '141.5000',
   '5. volume': '1797948421'},
  '2021-08-31': {'1. open': '146.3600',
   '2. high': '153.4900',
   '3. low': '144.5000',
   '4. close': '151.8300',
   '5. volume': '1462773381'},
  '2021-07-30': {'1. open': '136.6000',
   '2. high': '150.0000',
   '3. low': '135.7600',
   '4. close': '145.8600',
   '5. volume': '1916751489'},
  '2021-06-30': {'1. open': '125.0800',
   '2. high': '137.4100',
   '3. low': '123.1300',
   '4. close': '136.9600',
   '5. volume': '1606114354'},
  '2021-05-28': {'1. open': '132.0400',
   '2. high': '134.0700',
   '3. low': '122.2500',
   '4. close': '124.6100',
   '5. volume': '1711935110'},
  '2021-04-30': {'1. open': '123.6600',
   '2. high': '137.0700',
   '3. low': '122.4900',
   '4. close': '131.4600',
   '5. volume': '1889956694'},
  '2021-03-31': {'1. open': '123.7500',
   '2. high': '128.7200',
   '3. low': '116.2100',
   '4. close': '122.1500',
   '5. volume': '2650845211'},
  '2021-02-26': {'1. open': '133.7500',
   '2. high': '137.8770',
   '3. low': '118.3900',
   '4. close': '121.2600',
   '5. volume': '1825486961'},
  '2021-01-29': {'1. open': '133.5200',
   '2. high': '145.0900',
   '3. low': '126.3820',
   '4. close': '131.9600',
   '5. volume': '2239366098'},
  '2020-12-31': {'1. open': '121.0100',
   '2. high': '138.7890',
   '3. low': '120.0100',
   '4. close': '132.6900',
   '5. volume': '2319687808'},
  '2020-11-30': {'1. open': '109.1100',
   '2. high': '121.9900',
   '3. low': '107.3200',
   '4. close': '119.0500',
   '5. volume': '2122724412'},
  '2020-10-30': {'1. open': '117.6400',
   '2. high': '125.3900',
   '3. low': '107.7200',
   '4. close': '108.8600',
   '5. volume': '2895317580'},
  '2020-09-30': {'1. open': '132.7600',
   '2. high': '137.9800',
   '3. low': '103.1000',
   '4. close': '115.8100',
   '5. volume': '3886793083'},
  '2020-08-31': {'1. open': '432.8000',
   '2. high': '515.1400',
   '3. low': '126.0000',
   '4. close': '129.0400',
   '5. volume': '1184207050'},
  '2020-07-31': {'1. open': '365.1200',
   '2. high': '425.6600',
   '3. low': '356.5800',
   '4. close': '425.0400',
   '5. volume': '755162226'},
  '2020-06-30': {'1. open': '317.7500',
   '2. high': '372.3800',
   '3. low': '317.2100',
   '4. close': '364.8000',
   '5. volume': '810900890'},
  '2020-05-29': {'1. open': '286.2500',
   '2. high': '324.2400',
   '3. low': '285.8500',
   '4. close': '317.9400',
   '5. volume': '701660022'},
  '2020-04-30': {'1. open': '246.5000',
   '2. high': '294.5300',
   '3. low': '236.9000',
   '4. close': '293.8000',
   '5. volume': '816530808'},
  '2020-03-31': {'1. open': '282.2800',
   '2. high': '304.0000',
   '3. low': '212.6100',
   '4. close': '254.2900',
   '5. volume': '1570331732'},
  '2020-02-28': {'1. open': '304.3000',
   '2. high': '327.2200',
   '3. low': '256.3700',
   '4. close': '273.3600',
   '5. volume': '755223231'},
  '2020-01-31': {'1. open': '296.2400',
   '2. high': '327.8500',
   '3. low': '292.7500',
   '4. close': '309.5100',
   '5. volume': '734044103'},
  '2019-12-31': {'1. open': '267.2700',
   '2. high': '293.9700',
   '3. low': '256.2900',
   '4. close': '293.6500',
   '5. volume': '598871365'},
  '2019-11-29': {'1. open': '249.5400',
   '2. high': '268.0000',
   '3. low': '249.1600',
   '4. close': '267.2500',
   '5. volume': '448922253'},
  '2019-10-31': {'1. open': '225.0700',
   '2. high': '249.7500',
   '3. low': '215.1300',
   '4. close': '248.7600',
   '5. volume': '621478768'},
  '2019-09-30': {'1. open': '206.4300',
   '2. high': '226.4200',
   '3. low': '204.2200',
   '4. close': '223.9700',
   '5. volume': '547408488'},
  '2019-08-30': {'1. open': '213.9000',
   '2. high': '218.0300',
   '3. low': '192.5800',
   '4. close': '208.7400',
   '5. volume': '683515746'},
  '2019-07-31': {'1. open': '203.1700',
   '2. high': '221.3700',
   '3. low': '198.4100',
   '4. close': '213.0400',
   '5. volume': '473957094'},
  '2019-06-28': {'1. open': '175.6000',
   '2. high': '201.5700',
   '3. low': '170.2700',
   '4. close': '197.9200',
   '5. volume': '515218768'},
  '2019-05-31': {'1. open': '209.8800',
   '2. high': '215.3100',
   '3. low': '174.9900',
   '4. close': '175.0700',
   '5. volume': '739456573'},
  '2019-04-30': {'1. open': '191.6400',
   '2. high': '208.4800',
   '3. low': '188.3800',
   '4. close': '200.6700',
   '5. volume': '506117812'},
  '2019-03-29': {'1. open': '174.2800',
   '2. high': '197.6900',
   '3. low': '169.5000',
   '4. close': '189.9500',
   '5. volume': '650981384'},
  '2019-02-28': {'1. open': '166.9600',
   '2. high': '175.8700',
   '3. low': '165.9300',
   '4. close': '173.1500',
   '5. volume': '472540723'},
  '2019-01-31': {'1. open': '154.8900',
   '2. high': '169.0000',
   '3. low': '142.0000',
   '4. close': '166.4400',
   '5. volume': '828099179'},
  '2018-12-31': {'1. open': '184.4600',
   '2. high': '184.9400',
   '3. low': '146.5900',
   '4. close': '157.7400',
   '5. volume': '898917007'},
  '2018-11-30': {'1. open': '219.0500',
   '2. high': '222.3600',
   '3. low': '170.2600',
   '4. close': '178.5800',
   '5. volume': '961321947'},
  '2018-10-31': {'1. open': '227.9500',
   '2. high': '233.4700',
   '3. low': '206.0900',
   '4. close': '218.8600',
   '5. volume': '789748068'},
  '2018-09-28': {'1. open': '228.4100',
   '2. high': '229.6700',
   '3. low': '215.3000',
   '4. close': '225.7400',
   '5. volume': '678972040'},
  '2018-08-31': {'1. open': '199.1300',
   '2. high': '228.8700',
   '3. low': '197.3100',
   '4. close': '227.6300',
   '5. volume': '700318837'},
  '2018-07-31': {'1. open': '183.8200',
   '2. high': '195.9600',
   '3. low': '183.4200',
   '4. close': '190.2900',
   '5. volume': '393843881'},
  '2018-06-29': {'1. open': '187.9900',
   '2. high': '194.2000',
   '3. low': '180.7300',
   '4. close': '185.1100',
   '5. volume': '527624365'},
  '2018-05-31': {'1. open': '166.4100',
   '2. high': '190.3700',
   '3. low': '165.2700',
   '4. close': '186.8700',
   '5. volume': '620976206'},
  '2018-04-30': {'1. open': '166.6400',
   '2. high': '178.9400',
   '3. low': '160.6300',
   '4. close': '165.2600',
   '5. volume': '666360147'},
  '2018-03-29': {'1. open': '178.5400',
   '2. high': '183.5000',
   '3. low': '164.9400',
   '4. close': '167.7800',
   '5. volume': '701387082'},
  '2018-02-28': {'1. open': '167.1700',
   '2. high': '180.6200',
   '3. low': '150.2400',
   '4. close': '178.1200',
   '5. volume': '888378184'},
  '2018-01-31': {'1. open': '170.1600',
   '2. high': '180.1000',
   '3. low': '164.7000',
   '4. close': '167.4300',
   '5. volume': '639245534'},
  '2017-12-29': {'1. open': '169.9500',
   '2. high': '177.2000',
   '3. low': '166.4600',
   '4. close': '169.2300',
   '5. volume': '518560008'},
  '2017-11-30': {'1. open': '169.8700',
   '2. high': '176.2400',
   '3. low': '165.2800',
   '4. close': '171.8500',
   '5. volume': '581374608'},
  '2017-10-31': {'1. open': '154.2600',
   '2. high': '169.6499',
   '3. low': '152.4600',
   '4. close': '169.0400',
   '5. volume': '496135305'},
  '2017-09-29': {'1. open': '164.8000',
   '2. high': '164.9400',
   '3. low': '149.1600',
   '4. close': '154.1200',
   '5. volume': '669594016'},
  '2017-08-31': {'1. open': '149.1000',
   '2. high': '164.5200',
   '3. low': '148.4100',
   '4. close': '164.0000',
   '5. volume': '638221161'},
  '2017-07-31': {'1. open': '144.8800',
   '2. high': '153.9900',
   '3. low': '142.4100',
   '4. close': '148.7300',
   '5. volume': '411377229'},
  '2017-06-30': {'1. open': '153.1700',
   '2. high': '155.9800',
   '3. low': '142.2000',
   '4. close': '144.0200',
   '5. volume': '664986406'},
  '2017-05-31': {'1. open': '145.1000',
   '2. high': '156.6500',
   '3. low': '144.2700',
   '4. close': '152.7600',
   '5. volume': '635292989'},
  '2017-04-28': {'1. open': '143.7100',
   '2. high': '145.4600',
   '3. low': '140.0600',
   '4. close': '143.6500',
   '5. volume': '371280180'},
  '2017-03-31': {'1. open': '137.8900',
   '2. high': '144.5000',
   '3. low': '137.0500',
   '4. close': '143.6600',
   '5. volume': '562091214'},
  '2017-02-28': {'1. open': '127.0300',
   '2. high': '137.4800',
   '3. low': '127.0100',
   '4. close': '136.9900',
   '5. volume': '574968547'},
  '2017-01-31': {'1. open': '115.8000',
   '2. high': '122.4400',
   '3. low': '114.7600',
   '4. close': '121.3500',
   '5. volume': '563331160'},
  '2016-12-30': {'1. open': '110.3650',
   '2. high': '118.0166',
   '3. low': '108.2500',
   '4. close': '115.8200',
   '5. volume': '608771645'},
  '2016-11-30': {'1. open': '113.4600',
   '2. high': '113.7700',
   '3. low': '104.0800',
   '4. close': '110.5200',
   '5. volume': '721554967'},
  '2016-10-31': {'1. open': '112.7100',
   '2. high': '118.6900',
   '3. low': '112.2800',
   '4. close': '113.5400',
   '5. volume': '686914224'},
  '2016-09-30': {'1. open': '106.1400',
   '2. high': '116.1800',
   '3. low': '102.5300',
   '4. close': '113.0500',
   '5. volume': '970096738'},
  '2016-08-31': {'1. open': '104.4100',
   '2. high': '110.2300',
   '3. low': '104.0000',
   '4. close': '106.1000',
   '5. volume': '630128567'},
  '2016-07-29': {'1. open': '95.4900',
   '2. high': '104.5500',
   '3. low': '94.3700',
   '4. close': '104.2100',
   '5. volume': '685779613'},
  '2016-06-30': {'1. open': '99.0200',
   '2. high': '101.8900',
   '3. low': '91.5000',
   '4. close': '95.6000',
   '5. volume': '780630235'},
  '2016-05-31': {'1. open': '93.9650',
   '2. high': '100.7300',
   '3. low': '89.4700',
   '4. close': '99.8600',
   '5. volume': '901144768'},
  '2016-04-29': {'1. open': '108.7800',
   '2. high': '112.3900',
   '3. low': '92.5100',
   '4. close': '93.7400',
   '5. volume': '872383623'},
  '2016-03-31': {'1. open': '97.6500',
   '2. high': '110.4200',
   '3. low': '97.4200',
   '4. close': '108.9900',
   '5. volume': '745756771'},
  '2016-02-29': {'1. open': '96.4700',
   '2. high': '98.8900',
   '3. low': '92.5900',
   '4. close': '96.6900',
   '5. volume': '810862547'},
  '2016-01-29': {'1. open': '102.6100',
   '2. high': '105.8500',
   '3. low': '92.3900',
   '4. close': '97.3400',
   '5. volume': '1271848087'},
  '2015-12-31': {'1. open': '118.7500',
   '2. high': '119.8600',
   '3. low': '104.8200',
   '4. close': '105.2600',
   '5. volume': '922626259'},
  '2015-11-30': {'1. open': '119.8700',
   '2. high': '123.8200',
   '3. low': '111.0000',
   '4. close': '118.3000',
   '5. volume': '750606735'},
  '2015-10-30': {'1. open': '109.0700',
   '2. high': '121.2200',
   '3. low': '107.3100',
   '4. close': '119.5000',
   '5. volume': '1113703829'},
  '2015-09-30': {'1. open': '110.1800',
   '2. high': '116.8900',
   '3. low': '107.3600',
   '4. close': '109.9500',
   '5. volume': '1203789074'},
  '2015-08-31': {'1. open': '121.5000',
   '2. high': '122.5700',
   '3. low': '92.0000',
   '4. close': '112.7600',
   '5. volume': '1606359115'},
  '2015-07-31': {'1. open': '126.9000',
   '2. high': '132.9700',
   '3. low': '119.2200',
   '4. close': '121.3000',
   '5. volume': '1058280697'},
  '2015-06-30': {'1. open': '131.2000',
   '2. high': '131.3900',
   '3. low': '124.4800',
   '4. close': '125.4250',
   '5. volume': '878606841'},
  '2015-05-29': {'1. open': '126.1000',
   '2. high': '132.9700',
   '3. low': '123.3600',
   '4. close': '130.2800',
   '5. volume': '954152126'},
  '2015-04-30': {'1. open': '124.8200',
   '2. high': '134.5400',
   '3. low': '123.1000',
   '4. close': '125.1500',

In [ ]:
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=AApl&apikey={api}'
r=requests.get(url)
data=r.json()
print(data)

{'Information': 'Thank you for using Alpha Vantage! Please consider spreading out your free API requests more sparingly (1 request per second). You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to lift the free key rate limit (25 requests per day), raise the per-second burst limit, and instantly unlock all premium endpoints'}

In [ ]:
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=AApl&apikey={api}'
r=requests.get(url)
data=BeautifulSoup(r.content)
print(data)

<html><body>{
    "Information": "Thank you for using Alpha Vantage! Please consider spreading out your free API requests more sparingly (1 request per second). You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to lift the free key rate limit (25 requests per day), raise the per-second burst limit, and instantly unlock all premium endpoints"
}</body></html>

In [ ]:
url=f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=AApl&apikey={api} &datatype=csv'
r=requests.get(url).content
data=pd.read_csv(io.StringIO(r.decode('utf-8')))
print(data)

       timestamp     open    high       low   close     volume
0     2026-06-04  309.625  316.94  305.0200  311.23  189090488
1     2026-05-29  309.560  315.00  307.6700  312.06  216678554
2     2026-05-22  300.240  311.40  294.9100  308.82  200669745
3     2026-05-15  291.979  303.20  290.2300  300.23  230867432
4     2026-05-08  279.655  294.76  274.8601  293.32  252233246
...          ...      ...     ...       ...     ...        ...
1382  1999-12-10  114.560  118.00   99.0000  103.00   25152800
1383  1999-12-03   94.250  115.56   93.2500  115.00   28046300
1384  1999-11-26   91.750   95.50   88.5000   95.06    9757600
1385  1999-11-19   89.620   94.75   88.0600   92.44   13711000
1386  1999-11-12   87.750   97.73   86.7500   90.62   25776200

[1387 rows x 6 columns]

In [ ]:
data.head()

    timestamp     open    high       low   close     volume
0  2026-06-04  309.625  316.94  305.0200  311.23  189090488
1  2026-05-29  309.560  315.00  307.6700  312.06  216678554
2  2026-05-22  300.240  311.40  294.9100  308.82  200669745
3  2026-05-15  291.979  303.20  290.2300  300.23  230867432
4  2026-05-08  279.655  294.76  274.8601  293.32  252233246

In [ ]:
apple , metaData = ts1.get_monthly("AApl")

In [ ]:
metaData

{'1. Information': 'Monthly Prices (open, high, low, close) and Volumes',
 '2. Symbol': 'AApl',
 '3. Last Refreshed': '2026-06-04',
 '4. Time Zone': 'US/Eastern'}

In [ ]:
apple

{'2026-06-04': {'1. open': '309.6250',
  '2. high': '316.9400',
  '3. low': '305.0200',
  '4. close': '311.2300',
  '5. volume': '189090488'},
 '2026-05-29': {'1. open': '278.8550',
  '2. high': '315.0000',
  '3. low': '274.8601',
  '4. close': '312.0600',
  '5. volume': '980364419'},
 '2026-04-30': {'1. open': '254.0800',
  '2. high': '276.0000',
  '3. low': '245.7000',
  '4. close': '271.3500',
  '5. volume': '907538475'},
 '2026-03-31': {'1. open': '262.4100',
  '2. high': '266.5300',
  '3. low': '245.5100',
  '4. close': '253.7900',
  '5. volume': '900035757'},
 '2026-02-27': {'1. open': '260.0300',
  '2. high': '280.9050',
  '3. low': '255.4500',
  '4. close': '264.1800',
  '5. volume': '988325816'},
 '2026-01-30': {'1. open': '272.2550',
  '2. high': '277.8400',
  '3. low': '243.4200',
  '4. close': '259.4800',
  '5. volume': '1036170325'},
 '2025-12-31': {'1. open': '278.0100',
  '2. high': '288.6200',
  '3. low': '266.9500',
  '4. close': '271.8600',
  '5. volume': '922283649'},
 '2025-11-28': {'1. open': '270.4200',
  '2. high': '280.3800',
  '3. low': '265.3200',
  '4. close': '278.8500',
  '5. volume': '876481453'},
 '2025-10-31': {'1. open': '255.0400',
  '2. high': '277.3200',
  '3. low': '244.0000',
  '4. close': '270.3700',
  '5. volume': '1097142365'},
 '2025-09-30': {'1. open': '229.2500',
  '2. high': '257.6000',
  '3. low': '225.9500',
  '4. close': '254.6300',
  '5. volume': '1265170319'},
 '2025-08-29': {'1. open': '210.8650',
  '2. high': '235.1200',
  '3. low': '201.5000',
  '4. close': '232.1400',
  '5. volume': '1218125232'},
 '2025-07-31': {'1. open': '206.6650',
  '2. high': '216.2300',
  '3. low': '206.1401',
  '4. close': '207.5700',
  '5. volume': '1079935847'},
 '2025-06-30': {'1. open': '200.2800',
  '2. high': '207.3900',
  '3. low': '195.0700',
  '4. close': '205.1700',
  '5. volume': '1100504397'},
 '2025-05-30': {'1. open': '209.0800',
  '2. high': '214.5600',
  '3. low': '193.2500',
  '4. close': '200.8500',
  '5. volume': '1195889556'},
 '2025-04-30': {'1. open': '219.8050',
  '2. high': '225.1900',
  '3. low': '169.2101',
  '4. close': '212.5000',
  '5. volume': '1607318483'},
 '2025-03-31': {'1. open': '241.7900',
  '2. high': '244.0272',
  '3. low': '208.4200',
  '4. close': '222.1300',
  '5. volume': '1114686136'},
 '2025-02-28': {'1. open': '229.9900',
  '2. high': '250.0000',
  '3. low': '225.7000',
  '4. close': '241.8400',
  '5. volume': '862317019'},
 '2025-01-31': {'1. open': '248.9300',
  '2. high': '249.1000',
  '3. low': '219.3800',
  '4. close': '236.0000',
  '5. volume': '1200291603'},
 '2024-12-31': {'1. open': '237.2700',
  '2. high': '260.1000',
  '3. low': '237.1600',
  '4. close': '250.4200',
  '5. volume': '977942014'},
 '2024-11-29': {'1. open': '220.9650',
  '2. high': '237.8100',
  '3. low': '219.7100',
  '4. close': '237.3300',
  '5. volume': '891640714'},
 '2024-10-31': {'1. open': '229.5200',
  '2. high': '237.4900',
  '3. low': '221.3300',
  '4. close': '225.9100',
  '5. volume': '930835961'},
 '2024-09-30': {'1. open': '228.5500',
  '2. high': '233.0900',
  '3. low': '213.9200',
  '4. close': '233.0000',
  '5. volume': '1231814423'},
 '2024-08-30': {'1. open': '224.3700',
  '2. high': '232.9200',
  '3. low': '196.0000',
  '4. close': '229.0000',
  '5. volume': '1122666993'},
 '2024-07-31': {'1. open': '212.0900',
  '2. high': '237.2300',
  '3. low': '211.9200',
  '4. close': '222.0800',
  '5. volume': '1153193377'},
 '2024-06-28': {'1. open': '192.9000',
  '2. high': '220.2000',
  '3. low': '192.1500',
  '4. close': '210.6200',
  '5. volume': '1723984420'},
 '2024-05-31': {'1. open': '169.5800',
  '2. high': '193.0000',
  '3. low': '169.1100',
  '4. close': '192.2500',
  '5. volume': '1336570142'},
 '2024-04-30': {'1. open': '171.1900',
  '2. high': '178.3600',
  '3. low': '164.0750',
  '4. close': '170.3300',
  '5. volume': '1240410671'},
 '2024-03-28': {'1. open': '179.5500',
  '2. high': '180.5300',
  '3. low': '168.4900',
  '4. close': '171.4800',
  '5. volume': '1430780147'},
 '2024-02-29': {'1. open': '183.9850',
  '2. high': '191.0500',
  '3. low': '179.2500',
  '4. close': '180.7500',
  '5. volume': '1161711745'},
 '2024-01-31': {'1. open': '187.1500',
  '2. high': '196.3800',
  '3. low': '180.1700',
  '4. close': '184.4000',
  '5. volume': '1187139861'},
 '2023-12-29': {'1. open': '190.3300',
  '2. high': '199.6200',
  '3. low': '187.4511',
  '4. close': '192.5300',
  '5. volume': '1062317718'},
 '2023-11-30': {'1. open': '171.0000',
  '2. high': '192.9300',
  '3. low': '170.1200',
  '4. close': '189.9500',
  '5. volume': '1099760711'},
 '2023-10-31': {'1. open': '171.2200',
  '2. high': '182.3400',
  '3. low': '165.6700',
  '4. close': '170.7700',
  '5. volume': '1172845791'},
 '2023-09-29': {'1. open': '189.4850',
  '2. high': '189.9800',
  '3. low': '167.6200',
  '4. close': '171.2100',
  '5. volume': '1337873796'},
 '2023-08-31': {'1. open': '196.2350',
  '2. high': '196.7300',
  '3. low': '171.9600',
  '4. close': '187.8700',
  '5. volume': '1323817340'},
 '2023-07-31': {'1. open': '193.7800',
  '2. high': '198.2300',
  '3. low': '186.6000',
  '4. close': '196.4500',
  '5. volume': '996368613'},
 '2023-06-30': {'1. open': '177.7000',
  '2. high': '194.4800',
  '3. low': '176.9306',
  '4. close': '193.9700',
  '5. volume': '1297863403'},
 '2023-05-31': {'1. open': '169.2800',
  '2. high': '179.3500',
  '3. low': '164.3100',
  '4. close': '177.2500',
  '5. volume': '1275052503'},
 '2023-04-28': {'1. open': '164.2700',
  '2. high': '169.8500',
  '3. low': '159.7800',
  '4. close': '169.6800',
  '5. volume': '967580718'},
 '2023-03-31': {'1. open': '146.8300',
  '2. high': '165.0000',
  '3. low': '143.9000',
  '4. close': '164.9000',
  '5. volume': '1520461315'},
 '2023-02-28': {'1. open': '143.9700',
  '2. high': '157.3800',
  '3. low': '141.3200',
  '4. close': '147.4100',
  '5. volume': '1307294493'},
 '2023-01-31': {'1. open': '130.2800',
  '2. high': '147.2300',
  '3. low': '124.1700',
  '4. close': '144.2900',
  '5. volume': '1443652725'},
 '2022-12-30': {'1. open': '148.2100',
  '2. high': '150.9199',
  '3. low': '125.8700',
  '4. close': '129.9300',
  '5. volume': '1675731304'},
 '2022-11-30': {'1. open': '155.0800',
  '2. high': '155.4500',
  '3. low': '134.3800',
  '4. close': '148.0300',
  '5. volume': '1724948219'},
 '2022-10-31': {'1. open': '138.2100',
  '2. high': '157.5000',
  '3. low': '134.3700',
  '4. close': '153.3400',
  '5. volume': '1868381344'},
 '2022-09-30': {'1. open': '156.6400',
  '2. high': '164.2600',
  '3. low': '138.0000',
  '4. close': '138.2000',
  '5. volume': '2083968147'},
 '2022-08-31': {'1. open': '161.0100',
  '2. high': '176.1500',
  '3. low': '157.1400',
  '4. close': '157.2200',
  '5. volume': '1509735435'},
 '2022-07-29': {'1. open': '136.0400',
  '2. high': '163.6300',
  '3. low': '135.6600',
  '4. close': '162.5100',
  '5. volume': '1447364668'},
 '2022-06-30': {'1. open': '149.9000',
  '2. high': '151.7400',
  '3. low': '129.0400',
  '4. close': '136.7200',
  '5. volume': '1749297959'},
 '2022-05-31': {'1. open': '156.7100',
  '2. high': '166.4800',
  '3. low': '132.6100',
  '4. close': '148.8400',
  '5. volume': '2400305601'},
 '2022-04-29': {'1. open': '174.0300',
  '2. high': '178.4900',
  '3. low': '155.3800',
  '4. close': '157.6500',
  '5. volume': '1683547838'},
 '2022-03-31': {'1. open': '164.6950',
  '2. high': '179.6100',
  '3. low': '150.1000',
  '4. close': '174.6100',
  '5. volume': '2171827429'},
 '2022-02-28': {'1. open': '174.0100',
  '2. high': '176.6500',
  '3. low': '152.0000',
  '4. close': '165.1200',
  '5. volume': '1628570227'},
 '2022-01-31': {'1. open': '177.8300',
  '2. high': '182.9400',
  '3. low': '154.7000',
  '4. close': '174.7800',
  '5. volume': '2106513962'},
 '2021-12-31': {'1. open': '167.4800',
  '2. high': '182.1300',
  '3. low': '157.8000',
  '4. close': '177.5700',
  '5. volume': '2443227128'},
 '2021-11-30': {'1. open': '148.9850',
  '2. high': '165.7000',
  '3. low': '147.4800',
  '4. close': '165.3000',
  '5. volume': '1688864233'},
 '2021-10-29': {'1. open': '141.9000',
  '2. high': '153.1650',
  '3. low': '138.2700',
  '4. close': '149.8000',
  '5. volume': '1565079040'},
 '2021-09-30': {'1. open': '152.8300',
  '2. high': '157.2600',
  '3. low': '141.2700',
  '4. close': '141.5000',
  '5. volume': '1797948421'},
 '2021-08-31': {'1. open': '146.3600',
  '2. high': '153.4900',
  '3. low': '144.5000',
  '4. close': '151.8300',
  '5. volume': '1462773381'},
 '2021-07-30': {'1. open': '136.6000',
  '2. high': '150.0000',
  '3. low': '135.7600',
  '4. close': '145.8600',
  '5. volume': '1916751489'},
 '2021-06-30': {'1. open': '125.0800',
  '2. high': '137.4100',
  '3. low': '123.1300',
  '4. close': '136.9600',
  '5. volume': '1606114354'},
 '2021-05-28': {'1. open': '132.0400',
  '2. high': '134.0700',
  '3. low': '122.2500',
  '4. close': '124.6100',
  '5. volume': '1711935110'},
 '2021-04-30': {'1. open': '123.6600',
  '2. high': '137.0700',
  '3. low': '122.4900',
  '4. close': '131.4600',
  '5. volume': '1889956694'},
 '2021-03-31': {'1. open': '123.7500',
  '2. high': '128.7200',
  '3. low': '116.2100',
  '4. close': '122.1500',
  '5. volume': '2650845211'},
 '2021-02-26': {'1. open': '133.7500',
  '2. high': '137.8770',
  '3. low': '118.3900',
  '4. close': '121.2600',
  '5. volume': '1825486961'},
 '2021-01-29': {'1. open': '133.5200',
  '2. high': '145.0900',
  '3. low': '126.3820',
  '4. close': '131.9600',
  '5. volume': '2239366098'},
 '2020-12-31': {'1. open': '121.0100',
  '2. high': '138.7890',
  '3. low': '120.0100',
  '4. close': '132.6900',
  '5. volume': '2319687808'},
 '2020-11-30': {'1. open': '109.1100',
  '2. high': '121.9900',
  '3. low': '107.3200',
  '4. close': '119.0500',
  '5. volume': '2122724412'},
 '2020-10-30': {'1. open': '117.6400',
  '2. high': '125.3900',
  '3. low': '107.7200',
  '4. close': '108.8600',
  '5. volume': '2895317580'},
 '2020-09-30': {'1. open': '132.7600',
  '2. high': '137.9800',
  '3. low': '103.1000',
  '4. close': '115.8100',
  '5. volume': '3886793083'},
 '2020-08-31': {'1. open': '432.8000',
  '2. high': '515.1400',
  '3. low': '126.0000',
  '4. close': '129.0400',
  '5. volume': '1184207050'},
 '2020-07-31': {'1. open': '365.1200',
  '2. high': '425.6600',
  '3. low': '356.5800',
  '4. close': '425.0400',
  '5. volume': '755162226'},
 '2020-06-30': {'1. open': '317.7500',
  '2. high': '372.3800',
  '3. low': '317.2100',
  '4. close': '364.8000',
  '5. volume': '810900890'},
 '2020-05-29': {'1. open': '286.2500',
  '2. high': '324.2400',
  '3. low': '285.8500',
  '4. close': '317.9400',
  '5. volume': '701660022'},
 '2020-04-30': {'1. open': '246.5000',
  '2. high': '294.5300',
  '3. low': '236.9000',
  '4. close': '293.8000',
  '5. volume': '816530808'},
 '2020-03-31': {'1. open': '282.2800',
  '2. high': '304.0000',
  '3. low': '212.6100',
  '4. close': '254.2900',
  '5. volume': '1570331732'},
 '2020-02-28': {'1. open': '304.3000',
  '2. high': '327.2200',
  '3. low': '256.3700',
  '4. close': '273.3600',
  '5. volume': '755223231'},
 '2020-01-31': {'1. open': '296.2400',
  '2. high': '327.8500',
  '3. low': '292.7500',
  '4. close': '309.5100',
  '5. volume': '734044103'},
 '2019-12-31': {'1. open': '267.2700',
  '2. high': '293.9700',
  '3. low': '256.2900',
  '4. close': '293.6500',
  '5. volume': '598871365'},
 '2019-11-29': {'1. open': '249.5400',
  '2. high': '268.0000',
  '3. low': '249.1600',
  '4. close': '267.2500',
  '5. volume': '448922253'},
 '2019-10-31': {'1. open': '225.0700',
  '2. high': '249.7500',
  '3. low': '215.1300',
  '4. close': '248.7600',
  '5. volume': '621478768'},
 '2019-09-30': {'1. open': '206.4300',
  '2. high': '226.4200',
  '3. low': '204.2200',
  '4. close': '223.9700',
  '5. volume': '547408488'},
 '2019-08-30': {'1. open': '213.9000',
  '2. high': '218.0300',
  '3. low': '192.5800',
  '4. close': '208.7400',
  '5. volume': '683515746'},
 '2019-07-31': {'1. open': '203.1700',
  '2. high': '221.3700',
  '3. low': '198.4100',
  '4. close': '213.0400',
  '5. volume': '473957094'},
 '2019-06-28': {'1. open': '175.6000',
  '2. high': '201.5700',
  '3. low': '170.2700',
  '4. close': '197.9200',
  '5. volume': '515218768'},
 '2019-05-31': {'1. open': '209.8800',
  '2. high': '215.3100',
  '3. low': '174.9900',
  '4. close': '175.0700',
  '5. volume': '739456573'},
 '2019-04-30': {'1. open': '191.6400',
  '2. high': '208.4800',
  '3. low': '188.3800',
  '4. close': '200.6700',
  '5. volume': '506117812'},
 '2019-03-29': {'1. open': '174.2800',
  '2. high': '197.6900',
  '3. low': '169.5000',
  '4. close': '189.9500',
  '5. volume': '650981384'},
 '2019-02-28': {'1. open': '166.9600',
  '2. high': '175.8700',
  '3. low': '165.9300',
  '4. close': '173.1500',
  '5. volume': '472540723'},
 '2019-01-31': {'1. open': '154.8900',
  '2. high': '169.0000',
  '3. low': '142.0000',
  '4. close': '166.4400',
  '5. volume': '828099179'},
 '2018-12-31': {'1. open': '184.4600',
  '2. high': '184.9400',
  '3. low': '146.5900',
  '4. close': '157.7400',
  '5. volume': '898917007'},
 '2018-11-30': {'1. open': '219.0500',
  '2. high': '222.3600',
  '3. low': '170.2600',
  '4. close': '178.5800',
  '5. volume': '961321947'},
 '2018-10-31': {'1. open': '227.9500',
  '2. high': '233.4700',
  '3. low': '206.0900',
  '4. close': '218.8600',
  '5. volume': '789748068'},
 '2018-09-28': {'1. open': '228.4100',
  '2. high': '229.6700',
  '3. low': '215.3000',
  '4. close': '225.7400',
  '5. volume': '678972040'},
 '2018-08-31': {'1. open': '199.1300',
  '2. high': '228.8700',
  '3. low': '197.3100',
  '4. close': '227.6300',
  '5. volume': '700318837'},
 '2018-07-31': {'1. open': '183.8200',
  '2. high': '195.9600',
  '3. low': '183.4200',
  '4. close': '190.2900',
  '5. volume': '393843881'},
 '2018-06-29': {'1. open': '187.9900',
  '2. high': '194.2000',
  '3. low': '180.7300',
  '4. close': '185.1100',
  '5. volume': '527624365'},
 '2018-05-31': {'1. open': '166.4100',
  '2. high': '190.3700',
  '3. low': '165.2700',
  '4. close': '186.8700',
  '5. volume': '620976206'},
 '2018-04-30': {'1. open': '166.6400',
  '2. high': '178.9400',
  '3. low': '160.6300',
  '4. close': '165.2600',
  '5. volume': '666360147'},
 '2018-03-29': {'1. open': '178.5400',
  '2. high': '183.5000',
  '3. low': '164.9400',
  '4. close': '167.7800',
  '5. volume': '701387082'},
 '2018-02-28': {'1. open': '167.1700',
  '2. high': '180.6200',
  '3. low': '150.2400',
  '4. close': '178.1200',
  '5. volume': '888378184'},
 '2018-01-31': {'1. open': '170.1600',
  '2. high': '180.1000',
  '3. low': '164.7000',
  '4. close': '167.4300',
  '5. volume': '639245534'},
 '2017-12-29': {'1. open': '169.9500',
  '2. high': '177.2000',
  '3. low': '166.4600',
  '4. close': '169.2300',
  '5. volume': '518560008'},
 '2017-11-30': {'1. open': '169.8700',
  '2. high': '176.2400',
  '3. low': '165.2800',
  '4. close': '171.8500',
  '5. volume': '581374608'},
 '2017-10-31': {'1. open': '154.2600',
  '2. high': '169.6499',
  '3. low': '152.4600',
  '4. close': '169.0400',
  '5. volume': '496135305'},
 '2017-09-29': {'1. open': '164.8000',
  '2. high': '164.9400',
  '3. low': '149.1600',
  '4. close': '154.1200',
  '5. volume': '669594016'},
 '2017-08-31': {'1. open': '149.1000',
  '2. high': '164.5200',
  '3. low': '148.4100',
  '4. close': '164.0000',
  '5. volume': '638221161'},
 '2017-07-31': {'1. open': '144.8800',
  '2. high': '153.9900',
  '3. low': '142.4100',
  '4. close': '148.7300',
  '5. volume': '411377229'},
 '2017-06-30': {'1. open': '153.1700',
  '2. high': '155.9800',
  '3. low': '142.2000',
  '4. close': '144.0200',
  '5. volume': '664986406'},
 '2017-05-31': {'1. open': '145.1000',
  '2. high': '156.6500',
  '3. low': '144.2700',
  '4. close': '152.7600',
  '5. volume': '635292989'},
 '2017-04-28': {'1. open': '143.7100',
  '2. high': '145.4600',
  '3. low': '140.0600',
  '4. close': '143.6500',
  '5. volume': '371280180'},
 '2017-03-31': {'1. open': '137.8900',
  '2. high': '144.5000',
  '3. low': '137.0500',
  '4. close': '143.6600',
  '5. volume': '562091214'},
 '2017-02-28': {'1. open': '127.0300',
  '2. high': '137.4800',
  '3. low': '127.0100',
  '4. close': '136.9900',
  '5. volume': '574968547'},
 '2017-01-31': {'1. open': '115.8000',
  '2. high': '122.4400',
  '3. low': '114.7600',
  '4. close': '121.3500',
  '5. volume': '563331160'},
 '2016-12-30': {'1. open': '110.3650',
  '2. high': '118.0166',
  '3. low': '108.2500',
  '4. close': '115.8200',
  '5. volume': '608771645'},
 '2016-11-30': {'1. open': '113.4600',
  '2. high': '113.7700',
  '3. low': '104.0800',
  '4. close': '110.5200',
  '5. volume': '721554967'},
 '2016-10-31': {'1. open': '112.7100',
  '2. high': '118.6900',
  '3. low': '112.2800',
  '4. close': '113.5400',
  '5. volume': '686914224'},
 '2016-09-30': {'1. open': '106.1400',
  '2. high': '116.1800',
  '3. low': '102.5300',
  '4. close': '113.0500',
  '5. volume': '970096738'},
 '2016-08-31': {'1. open': '104.4100',
  '2. high': '110.2300',
  '3. low': '104.0000',
  '4. close': '106.1000',
  '5. volume': '630128567'},
 '2016-07-29': {'1. open': '95.4900',
  '2. high': '104.5500',
  '3. low': '94.3700',
  '4. close': '104.2100',
  '5. volume': '685779613'},
 '2016-06-30': {'1. open': '99.0200',
  '2. high': '101.8900',
  '3. low': '91.5000',
  '4. close': '95.6000',
  '5. volume': '780630235'},
 '2016-05-31': {'1. open': '93.9650',
  '2. high': '100.7300',
  '3. low': '89.4700',
  '4. close': '99.8600',
  '5. volume': '901144768'},
 '2016-04-29': {'1. open': '108.7800',
  '2. high': '112.3900',
  '3. low': '92.5100',
  '4. close': '93.7400',
  '5. volume': '872383623'},
 '2016-03-31': {'1. open': '97.6500',
  '2. high': '110.4200',
  '3. low': '97.4200',
  '4. close': '108.9900',
  '5. volume': '745756771'},
 '2016-02-29': {'1. open': '96.4700',
  '2. high': '98.8900',
  '3. low': '92.5900',
  '4. close': '96.6900',
  '5. volume': '810862547'},
 '2016-01-29': {'1. open': '102.6100',
  '2. high': '105.8500',
  '3. low': '92.3900',
  '4. close': '97.3400',
  '5. volume': '1271848087'},
 '2015-12-31': {'1. open': '118.7500',
  '2. high': '119.8600',
  '3. low': '104.8200',
  '4. close': '105.2600',
  '5. volume': '922626259'},
 '2015-11-30': {'1. open': '119.8700',
  '2. high': '123.8200',
  '3. low': '111.0000',
  '4. close': '118.3000',
  '5. volume': '750606735'},
 '2015-10-30': {'1. open': '109.0700',
  '2. high': '121.2200',
  '3. low': '107.3100',
  '4. close': '119.5000',
  '5. volume': '1113703829'},
 '2015-09-30': {'1. open': '110.1800',
  '2. high': '116.8900',
  '3. low': '107.3600',
  '4. close': '109.9500',
  '5. volume': '1203789074'},
 '2015-08-31': {'1. open': '121.5000',
  '2. high': '122.5700',
  '3. low': '92.0000',
  '4. close': '112.7600',
  '5. volume': '1606359115'},
 '2015-07-31': {'1. open': '126.9000',
  '2. high': '132.9700',
  '3. low': '119.2200',
  '4. close': '121.3000',
  '5. volume': '1058280697'},
 '2015-06-30': {'1. open': '131.2000',
  '2. high': '131.3900',
  '3. low': '124.4800',
  '4. close': '125.4250',
  '5. volume': '878606841'},
 '2015-05-29': {'1. open': '126.1000',
  '2. high': '132.9700',
  '3. low': '123.3600',
  '4. close': '130.2800',
  '5. volume': '954152126'},
 '2015-04-30': {'1. open': '124.8200',
  '2. high': '134.5400',
  '3. low': '123.1000',
  '4. close': '125.1500',
  '5. volume': '996135511'},
 '2015-03-31': {'1. open': '129.2500',
  '2. high': '130.2800',
  '3. low': '121.6300',
  '4. close': '124.4300',
  '5. volume': '1138641910'},
 '2015-02-27': {'1. open': '118.0500',
  '2. high': '133.6000',
  '3. low': '116.0800',
  '4. close': '128.4600',
  '5. volume': '1136535493'},
 '2015-01-30': {'1. open': '111.3900',
  '2. high': '120.0000',
  '3. low': '104.6300',
  '4. close': '117.1600',
  '5. volume': '1304879185'},
 '2014-12-31': {'1. open': '118.8100',
  '2. high': '119.2500',
  '3. low': '106.2600',
  '4. close': '110.3800',
  '5. volume': '1073775862'},
 '2014-11-28': {'1. open': '108.2200',
  '2. high': '119.7500',

In [ ]:
dF=pd.DataFrame(apple)

In [ ]:
df=dF.transpose().reset_index()
df

          index   1. open   2. high    3. low  4. close  5. volume
0    2026-06-04  309.6250  316.9400  305.0200  311.2300  189090488
1    2026-05-29  278.8550  315.0000  274.8601  312.0600  980364419
2    2026-04-30  254.0800  276.0000  245.7000  271.3500  907538475
3    2026-03-31  262.4100  266.5300  245.5100  253.7900  900035757
4    2026-02-27  260.0300  280.9050  255.4500  264.1800  988325816
..          ...       ...       ...       ...       ...        ...
314  2000-04-28  135.5000  139.5000  104.8700  124.0600   77342900
315  2000-03-31  118.5600  150.3800  114.0000  135.8100   77663900
316  2000-02-29  104.0000  119.9400   97.0000  114.6200   65355200
317  2000-01-31  104.8700  121.5000   86.5000  103.7500  112099800
318  1999-12-31  101.0000  118.0000   91.0600  102.8100   84091200

[319 rows x 6 columns]

In [ ]:
ts2=TimeSeries(key=api,output_format="pandas")

In [ ]:
ts2.get_monthly("AApl")

(            1. open  2. high    3. low  4. close    5. volume
 date
 2026-06-04  309.625  316.940  305.0200    311.23  189090488.0
 2026-05-29  278.855  315.000  274.8601    312.06  980364419.0
 2026-04-30  254.080  276.000  245.7000    271.35  907538475.0
 2026-03-31  262.410  266.530  245.5100    253.79  900035757.0
 2026-02-27  260.030  280.905  255.4500    264.18  988325816.0
 ...             ...      ...       ...       ...          ...
 2000-04-28  135.500  139.500  104.8700    124.06   77342900.0
 2000-03-31  118.560  150.380  114.0000    135.81   77663900.0
 2000-02-29  104.000  119.940   97.0000    114.62   65355200.0
 2000-01-31  104.870  121.500   86.5000    103.75  112099800.0
 1999-12-31  101.000  118.000   91.0600    102.81   84091200.0

 [319 rows x 5 columns],
 {'1. Information': 'Monthly Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'AApl',
  '3. Last Refreshed': '2026-06-04',
  '4. Time Zone': 'US/Eastern'})

In [ ]:
dfAppl,metaData=ts2.get_monthly("AApl")

In [ ]:
dfAppl.reset_index()

          date  1. open  2. high    3. low  4. close    5. volume
0   2026-06-04  309.625  316.940  305.0200    311.23  189090488.0
1   2026-05-29  278.855  315.000  274.8601    312.06  980364419.0
2   2026-04-30  254.080  276.000  245.7000    271.35  907538475.0
3   2026-03-31  262.410  266.530  245.5100    253.79  900035757.0
4   2026-02-27  260.030  280.905  255.4500    264.18  988325816.0
..         ...      ...      ...       ...       ...          ...
314 2000-04-28  135.500  139.500  104.8700    124.06   77342900.0
315 2000-03-31  118.560  150.380  114.0000    135.81   77663900.0
316 2000-02-29  104.000  119.940   97.0000    114.62   65355200.0
317 2000-01-31  104.870  121.500   86.5000    103.75  112099800.0
318 1999-12-31  101.000  118.000   91.0600    102.81   84091200.0

[319 rows x 6 columns]

In [ ]:
metaData

{'1. Information': 'Monthly Prices (open, high, low, close) and Volumes',
 '2. Symbol': 'AApl',
 '3. Last Refreshed': '2026-06-04',
 '4. Time Zone': 'US/Eastern'}

In [ ]:
url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol=AApl&apikey={api}'
r=requests.get(url)
fd=BeautifulSoup(r.content)
print(fd)

<html><body>{
    "symbol": "AAPL",
    "annualReports": [
        {
            "fiscalDateEnding": "2025-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "195201000000",
            "totalRevenue": "416161000000",
            "costOfRevenue": "220960000000",
            "costofGoodsAndServicesSold": "220960000000",
            "operatingIncome": "133050000000",
            "sellingGeneralAndAdministrative": "27601000000",
            "researchAndDevelopment": "34550000000",
            "operatingExpenses": "62151000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "None",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "None",
            "depreciation": "None",
            "depreciationAndAmortization": "11698000000",
            "incomeBeforeTax": "132729000000",
            "incomeTaxExpense": "20719000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "112010000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "132729000000",
            "ebitda": "144427000000",
            "netIncome": "112010000000"
        },
        {
            "fiscalDateEnding": "2024-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "180683000000",
            "totalRevenue": "391035000000",
            "costOfRevenue": "210352000000",
            "costofGoodsAndServicesSold": "210352000000",
            "operatingIncome": "123216000000",
            "sellingGeneralAndAdministrative": "26097000000",
            "researchAndDevelopment": "31370000000",
            "operatingExpenses": "57467000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "0",
            "interestIncome": "0",
            "interestExpense": "0",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "None",
            "depreciation": "None",
            "depreciationAndAmortization": "11445000000",
            "incomeBeforeTax": "123485000000",
            "incomeTaxExpense": "29749000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "93736000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "123216000000",
            "ebitda": "134661000000",
            "netIncome": "93736000000"
        },
        {
            "fiscalDateEnding": "2023-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "169148000000",
            "totalRevenue": "383285000000",
            "costOfRevenue": "214137000000",
            "costofGoodsAndServicesSold": "214137000000",
            "operatingIncome": "114301000000",
            "sellingGeneralAndAdministrative": "24932000000",
            "researchAndDevelopment": "29915000000",
            "operatingExpenses": "54847000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-183000000",
            "interestIncome": "3750000000",
            "interestExpense": "3933000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "-382000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11519000000",
            "incomeBeforeTax": "113736000000",
            "incomeTaxExpense": "16741000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "96995000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "114301000000",
            "ebitda": "125820000000",
            "netIncome": "96995000000"
        },
        {
            "fiscalDateEnding": "2022-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "170782000000",
            "totalRevenue": "394328000000",
            "costOfRevenue": "223546000000",
            "costofGoodsAndServicesSold": "223546000000",
            "operatingIncome": "119437000000",
            "sellingGeneralAndAdministrative": "25094000000",
            "researchAndDevelopment": "26251000000",
            "operatingExpenses": "51573000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-106000000",
            "interestIncome": "2825000000",
            "interestExpense": "2931000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "334000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11104000000",
            "incomeBeforeTax": "119103000000",
            "incomeTaxExpense": "19300000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "99803000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "119437000000",
            "ebitda": "130541000000",
            "netIncome": "99803000000"
        },
        {
            "fiscalDateEnding": "2021-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "152836000000",
            "totalRevenue": "365817000000",
            "costOfRevenue": "212981000000",
            "costofGoodsAndServicesSold": "212981000000",
            "operatingIncome": "108949000000",
            "sellingGeneralAndAdministrative": "21973000000",
            "researchAndDevelopment": "21914000000",
            "operatingExpenses": "43887000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "198000000",
            "interestIncome": "2843000000",
            "interestExpense": "2645000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "258000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11284000000",
            "incomeBeforeTax": "109207000000",
            "incomeTaxExpense": "14527000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "94680000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "111852000000",
            "ebitda": "123136000000",
            "netIncome": "94680000000"
        },
        {
            "fiscalDateEnding": "2020-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "104956000000",
            "totalRevenue": "274515000000",
            "costOfRevenue": "169559000000",
            "costofGoodsAndServicesSold": "169559000000",
            "operatingIncome": "66288000000",
            "sellingGeneralAndAdministrative": "19916000000",
            "researchAndDevelopment": "18752000000",
            "operatingExpenses": "38668000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "890000000",
            "interestIncome": "3763000000",
            "interestExpense": "2873000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "803000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11056000000",
            "incomeBeforeTax": "67091000000",
            "incomeTaxExpense": "9680000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "57411000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "69964000000",
            "ebitda": "81020000000",
            "netIncome": "57411000000"
        },
        {
            "fiscalDateEnding": "2019-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "98392000000",
            "totalRevenue": "260174000000",
            "costOfRevenue": "161782000000",
            "costofGoodsAndServicesSold": "161782000000",
            "operatingIncome": "63930000000",
            "sellingGeneralAndAdministrative": "18245000000",
            "researchAndDevelopment": "16217000000",
            "operatingExpenses": "34462000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "1385000000",
            "interestIncome": "4961000000",
            "interestExpense": "3576000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1807000000",
            "depreciation": "None",
            "depreciationAndAmortization": "12547000000",
            "incomeBeforeTax": "65737000000",
            "incomeTaxExpense": "10481000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "55256000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "69313000000",
            "ebitda": "81860000000",
            "netIncome": "55256000000"
        },
        {
            "fiscalDateEnding": "2018-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "101839000000",
            "totalRevenue": "265595000000",
            "costOfRevenue": "163756000000",
            "costofGoodsAndServicesSold": "163756000000",
            "operatingIncome": "70898000000",
            "sellingGeneralAndAdministrative": "16705000000",
            "researchAndDevelopment": "14236000000",
            "operatingExpenses": "30941000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "2446000000",
            "interestIncome": "5686000000",
            "interestExpense": "3240000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "2005000000",
            "depreciation": "None",
            "depreciationAndAmortization": "10903000000",
            "incomeBeforeTax": "72903000000",
            "incomeTaxExpense": "13372000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "59531000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "76143000000",
            "ebitda": "87046000000",
            "netIncome": "59531000000"
        },
        {
            "fiscalDateEnding": "2017-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "88186000000",
            "totalRevenue": "229234000000",
            "costOfRevenue": "141048000000",
            "costofGoodsAndServicesSold": "141048000000",
            "operatingIncome": "61344000000",
            "sellingGeneralAndAdministrative": "15261000000",
            "researchAndDevelopment": "11581000000",
            "operatingExpenses": "26842000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "2878000000",
            "interestIncome": "5201000000",
            "interestExpense": "2323000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "2745000000",
            "depreciation": "None",
            "depreciationAndAmortization": "10157000000",
            "incomeBeforeTax": "64089000000",
            "incomeTaxExpense": "15738000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "48351000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "66412000000",
            "ebitda": "76569000000",
            "netIncome": "48351000000"
        },
        {
            "fiscalDateEnding": "2016-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "84263000000",
            "totalRevenue": "215639000000",
            "costOfRevenue": "131376000000",
            "costofGoodsAndServicesSold": "131376000000",
            "operatingIncome": "60024000000",
            "sellingGeneralAndAdministrative": "14194000000",
            "researchAndDevelopment": "10045000000",
            "operatingExpenses": "24239000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "2543000000",
            "interestIncome": "3999000000",
            "interestExpense": "1456000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1348000000",
            "depreciation": "None",
            "depreciationAndAmortization": "10505000000",
            "incomeBeforeTax": "61372000000",
            "incomeTaxExpense": "15685000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "45687000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "62828000000",
            "ebitda": "73333000000",
            "netIncome": "45687000000"
        },
        {
            "fiscalDateEnding": "2015-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "93626000000",
            "totalRevenue": "233715000000",
            "costOfRevenue": "140089000000",
            "costofGoodsAndServicesSold": "140089000000",
            "operatingIncome": "71230000000",
            "sellingGeneralAndAdministrative": "14329000000",
            "researchAndDevelopment": "8067000000",
            "operatingExpenses": "22396000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "733000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1285000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11257000000",
            "incomeBeforeTax": "72515000000",
            "incomeTaxExpense": "19121000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "53394000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "73248000000",
            "ebitda": "84505000000",
            "netIncome": "53394000000"
        },
        {
            "fiscalDateEnding": "2014-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "70537000000",
            "totalRevenue": "182795000000",
            "costOfRevenue": "112258000000",
            "costofGoodsAndServicesSold": "112258000000",
            "operatingIncome": "52503000000",
            "sellingGeneralAndAdministrative": "11993000000",
            "researchAndDevelopment": "6041000000",
            "operatingExpenses": "18034000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "384000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "980000000",
            "depreciation": "None",
            "depreciationAndAmortization": "7946000000",
            "incomeBeforeTax": "53483000000",
            "incomeTaxExpense": "13973000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "39510000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "53867000000",
            "ebitda": "61813000000",
            "netIncome": "39510000000"
        },
        {
            "fiscalDateEnding": "2013-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "64304000000",
            "totalRevenue": "170910000000",
            "costOfRevenue": "106606000000",
            "costofGoodsAndServicesSold": "106606000000",
            "operatingIncome": "48999000000",
            "sellingGeneralAndAdministrative": "9730000000",
            "researchAndDevelopment": "4475000000",
            "operatingExpenses": "15305000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "136000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1156000000",
            "depreciation": "None",
            "depreciationAndAmortization": "6757000000",
            "incomeBeforeTax": "50155000000",
            "incomeTaxExpense": "13118000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "37037000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "50291000000",
            "ebitda": "57048000000",
            "netIncome": "37037000000"
        },
        {
            "fiscalDateEnding": "2012-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "68662000000",
            "totalRevenue": "156508000000",
            "costOfRevenue": "87846000000",
            "costofGoodsAndServicesSold": "87846000000",
            "operatingIncome": "55241000000",
            "sellingGeneralAndAdministrative": "9040000000",
            "researchAndDevelopment": "3381000000",
            "operatingExpenses": "13421000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "522000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "522000000",
            "depreciation": "None",
            "depreciationAndAmortization": "3277000000",
            "incomeBeforeTax": "55763000000",
            "incomeTaxExpense": "14030000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "41733000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "55763000000",
            "ebitda": "59040000000",
            "netIncome": "41733000000"
        },
        {
            "fiscalDateEnding": "2011-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "43818000000",
            "totalRevenue": "108249000000",
            "costOfRevenue": "64431000000",
            "costofGoodsAndServicesSold": "64431000000",
            "operatingIncome": "33790000000",
            "sellingGeneralAndAdministrative": "7599000000",
            "researchAndDevelopment": "2429000000",
            "operatingExpenses": "10028000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "415000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "415000000",
            "depreciation": "None",
            "depreciationAndAmortization": "1814000000",
            "incomeBeforeTax": "34205000000",
            "incomeTaxExpense": "8283000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "25922000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "34205000000",
            "ebitda": "36019000000",
            "netIncome": "25922000000"
        },
        {
            "fiscalDateEnding": "2010-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "25684000000",
            "totalRevenue": "65225000000",
            "costOfRevenue": "39541000000",
            "costofGoodsAndServicesSold": "39541000000",
            "operatingIncome": "18385000000",
            "sellingGeneralAndAdministrative": "5517000000",
            "researchAndDevelopment": "1782000000",
            "operatingExpenses": "7299000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "155000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "155000000",
            "depreciation": "None",
            "depreciationAndAmortization": "1027000000",
            "incomeBeforeTax": "18540000000",
            "incomeTaxExpense": "4527000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "14013000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "18385000000",
            "ebitda": "19412000000",
            "netIncome": "14013000000"
        },
        {
            "fiscalDateEnding": "2009-09-30",
            "reportedCurrency": "USD",
            "grossProfit": "16852000000",
            "totalRevenue": "42603000000",
            "costOfRevenue": "25751000000",
            "costofGoodsAndServicesSold": "25751000000",

In [ ]:
# link="https://www.alphavantage.co/query?function=EARNINGS"
# link="https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=USD&to_currency=JPY"
url=f'https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_WEEKLY&symbol=BTC&market=USD&apikey={api}'
# url = f'{link}&symbol=AApl&apikey={api}'
r=requests.get(url)
fd=BeautifulSoup(r.content)
print(fd)

<html><body>{
    "Meta Data": {
        "1. Information": "Weekly Prices and Volumes for Digital Currency",
        "2. Digital Currency Code": "BTC",
        "3. Digital Currency Name": "Bitcoin",
        "4. Market Code": "USD",
        "5. Market Name": "United States Dollar",
        "6. Last Refreshed": "2026-06-05 00:00:00",
        "7. Time Zone": "UTC"
    },
    "Time Series (Digital Currency Weekly)": {
        "2026-06-05": {
            "1. open": "73575.18000000",
            "2. high": "73978.52000000",
            "3. low": "61309.25000000",
            "4. close": "63846.26000000",
            "5. volume": "68111.49988664"
        },
        "2026-05-31": {
            "1. open": "76975.99000000",
            "2. high": "78015.46000000",
            "3. low": "72364.13000000",
            "4. close": "73575.17000000",
            "5. volume": "43304.98431196"
        },
        "2026-05-24": {
            "1. open": "77406.57000000",
            "2. high": "78123.68000000",
            "3. low": "74197.11000000",
            "4. close": "76975.99000000",
            "5. volume": "40201.14590375"
        },
        "2026-05-17": {
            "1. open": "82199.99000000",
            "2. high": "82379.00000000",
            "3. low": "76673.54000000",
            "4. close": "77407.59000000",
            "5. volume": "45805.14337810"
        },
        "2026-05-10": {
            "1. open": "78558.88000000",
            "2. high": "82814.23000000",
            "3. low": "78205.00000000",
            "4. close": "82199.99000000",
            "5. volume": "45098.01679231"
        },
        "2026-05-03": {
            "1. open": "78673.84000000",
            "2. high": "79496.00000000",
            "3. low": "74914.00000000",
            "4. close": "78558.89000000",
            "5. volume": "45860.20469277"
        },
        "2026-04-26": {
            "1. open": "73823.27000000",
            "2. high": "79523.00000000",
            "3. low": "73741.53000000",
            "4. close": "78673.83000000",
            "5. volume": "52241.43140732"
        },
        "2026-04-19": {
            "1. open": "70755.35000000",
            "2. high": "78390.00000000",
            "3. low": "70576.27000000",
            "4. close": "73823.14000000",
            "5. volume": "79547.52519065"
        },
        "2026-04-12": {
            "1. open": "69005.00000000",
            "2. high": "73822.95000000",
            "3. low": "67710.01000000",
            "4. close": "70755.35000000",
            "5. volume": "61435.73085478"
        },
        "2026-04-05": {
            "1. open": "65957.95000000",
            "2. high": "69285.99000000",
            "3. low": "65696.96000000",
            "4. close": "69005.00000000",
            "5. volume": "51562.01929144"
        },
        "2026-03-29": {
            "1. open": "67844.94000000",
            "2. high": "72030.29000000",
            "3. low": "64938.66000000",
            "4. close": "65956.94000000",
            "5. volume": "55765.16140931"
        },
        "2026-03-22": {
            "1. open": "72830.01000000",
            "2. high": "76022.60000000",
            "3. low": "67332.05000000",
            "4. close": "67844.94000000",
            "5. volume": "56119.92627955"
        },
        "2026-03-15": {
            "1. open": "65970.56000000",
            "2. high": "73968.00000000",
            "3. low": "65820.93000000",
            "4. close": "72830.01000000",
            "5. volume": "67450.45850290"
        },
        "2026-03-08": {
            "1. open": "65771.56000000",
            "2. high": "74100.00000000",
            "3. low": "65250.12000000",
            "4. close": "65970.56000000",
            "5. volume": "82426.13019768"
        },
        "2026-03-01": {
            "1. open": "67616.01000000",
            "2. high": "70020.00000000",
            "3. low": "62534.61000000",
            "4. close": "65769.00000000",
            "5. volume": "83598.17441290"
        },
        "2026-02-22": {
            "1. open": "68792.00000000",
            "2. high": "70089.99000000",
            "3. low": "65604.63000000",
            "4. close": "67617.98000000",
            "5. volume": "51842.25665886"
        },
        "2026-02-15": {
            "1. open": "70279.32000000",
            "2. high": "71380.13000000",
            "3. low": "65065.47000000",
            "4. close": "68792.00000000",
            "5. volume": "79714.58060286"
        },
        "2026-02-08": {
            "1. open": "76895.99000000",
            "2. high": "79339.00000000",
            "3. low": "60001.00000000",
            "4. close": "70279.33000000",
            "5. volume": "169949.50497032"
        },
        "2026-02-01": {
            "1. open": "86561.94000000",
            "2. high": "90476.81000000",
            "3. low": "75612.75000000",
            "4. close": "76895.53000000",
            "5. volume": "77825.94683402"
        },
        "2026-01-25": {
            "1. open": "93630.00000000",
            "2. high": "93630.00000000",
            "3. low": "86000.13000000",
            "4. close": "86561.94000000",
            "5. volume": "50354.68951885"
        },
        "2026-01-18": {
            "1. open": "90878.51000000",
            "2. high": "97963.62000000",
            "3. low": "90003.46000000",
            "4. close": "93633.53000000",
            "5. volume": "68801.72256238"
        },
        "2026-01-11": {
            "1. open": "91489.03000000",
            "2. high": "94825.27000000",
            "3. low": "89200.00000000",
            "4. close": "90872.01000000",
            "5. volume": "54920.82057330"
        },
        "2026-01-04": {
            "1. open": "87877.28000000",
            "2. high": "91764.64000000",
            "3. low": "86675.00000000",
            "4. close": "91494.00000000",
            "5. volume": "47996.29126177"
        },
        "2025-12-28": {
            "1. open": "88639.87000000",
            "2. high": "90541.80000000",
            "3. low": "86350.00000000",
            "4. close": "87877.29000000",
            "5. volume": "36267.90324035"
        },
        "2025-12-21": {
            "1. open": "88174.37000000",
            "2. high": "90336.36000000",
            "3. low": "84400.00000000",
            "4. close": "88639.95000000",
            "5. volume": "49681.18661870"
        },
        "2025-12-14": {
            "1. open": "90402.30000000",
            "2. high": "94640.66000000",
            "3. low": "87565.38000000",
            "4. close": "88171.61000000",
            "5. volume": "45872.74657174"
        },
        "2025-12-07": {
            "1. open": "90364.00000000",
            "2. high": "94181.41000000",
            "3. low": "83800.00000000",
            "4. close": "90402.29000000",
            "5. volume": "61166.09556452"
        },
        "2025-11-30": {
            "1. open": "86808.28000000",
            "2. high": "93161.86000000",
            "3. low": "85213.17000000",
            "4. close": "90369.51000000",
            "5. volume": "61144.39327768"
        },
        "2025-11-23": {
            "1. open": "94182.03000000",
            "2. high": "95950.00000000",
            "3. low": "80524.65000000",
            "4. close": "86808.28000000",
            "5. volume": "112330.60408656"
        },
        "2025-11-16": {
            "1. open": "104694.23000000",
            "2. high": "107482.00000000",
            "3. low": "92943.83000000",
            "4. close": "94183.97000000",
            "5. volume": "65039.16703014"
        },
        "2025-11-09": {
            "1. open": "110533.83000000",
            "2. high": "110749.00000000",
            "3. low": "98892.97000000",
            "4. close": "104694.95000000",
            "5. volume": "65935.89295614"
        },
        "2025-11-02": {
            "1. open": "114561.69000000",
            "2. high": "116410.06000000",
            "3. low": "106279.33000000",
            "4. close": "110536.01000000",
            "5. volume": "37769.71606216"
        },
        "2025-10-26": {
            "1. open": "108676.77000000",
            "2. high": "115542.00000000",
            "3. low": "106639.00000000",
            "4. close": "114548.09000000",
            "5. volume": "46571.80025821"
        },
        "2025-10-19": {
            "1. open": "115067.96000000",
            "2. high": "116077.51000000",
            "3. low": "103516.75000000",
            "4. close": "108676.78000000",
            "5. volume": "64554.53315024"
        },
        "2025-10-12": {
            "1. open": "123520.80000000",
            "2. high": "126296.00000000",
            "3. low": "107000.00000000",
            "4. close": "115067.98000000",
            "5. volume": "73716.51126655"
        },
        "2025-10-05": {
            "1. open": "112197.66000000",
            "2. high": "125750.00000000",
            "3. low": "111582.65000000",
            "4. close": "123520.79000000",
            "5. volume": "49462.68044524"
        },
        "2025-09-28": {
            "1. open": "115282.26000000",
            "2. high": "115441.37000000",
            "3. low": "108623.70000000",
            "4. close": "112197.67000000",
            "5. volume": "38310.34046273"
        },
        "2025-09-21": {
            "1. open": "115314.12000000",
            "2. high": "117998.17000000",
            "3. low": "114395.84000000",
            "4. close": "115282.27000000",
            "5. volume": "37222.96619062"
        },
        "2025-09-14": {
            "1. open": "111120.38000000",
            "2. high": "116833.25000000",
            "3. low": "110600.00000000",
            "4. close": "115314.13000000",
            "5. volume": "33777.20417193"
        },
        "2025-09-07": {
            "1. open": "108247.95000000",
            "2. high": "113390.00000000",
            "3. low": "107250.00000000",
            "4. close": "111129.61000000",
            "5. volume": "33740.89307684"
        },
        "2025-08-31": {
            "1. open": "113478.00000000",
            "2. high": "113645.32000000",
            "3. low": "107369.69000000",
            "4. close": "108247.95000000",
            "5. volume": "39370.76296228"
        },
        "2025-08-24": {
            "1. open": "117488.59000000",
            "2. high": "117633.80000000",
            "3. low": "110635.00000000",
            "4. close": "113478.00000000",
            "5. volume": "41875.36196815"
        },
        "2025-08-17": {
            "1. open": "119309.37000000",
            "2. high": "124533.00000000",
            "3. low": "116859.32000000",
            "4. close": "117488.60000000",
            "5. volume": "39297.31330514"
        },
        "2025-08-10": {
            "1. open": "114215.70000000",
            "2. high": "119324.08000000",
            "3. low": "112622.14000000",
            "4. close": "119309.37000000",
            "5. volume": "30191.65189929"
        },
        "2025-08-03": {
            "1. open": "119465.52000000",
            "2. high": "119839.00000000",
            "3. low": "111903.68000000",
            "4. close": "114215.73000000",
            "5. volume": "37369.17921146"
        },
        "2025-07-27": {
            "1. open": "117315.68000000",
            "2. high": "120300.00000000",
            "3. low": "114750.00000000",
            "4. close": "119465.52000000",
            "5. volume": "62285.48155696"
        },
        "2025-07-20": {
            "1. open": "119130.81000000",
            "2. high": "123231.07000000",
            "3. low": "115697.37000000",
            "4. close": "117312.70000000",
            "5. volume": "67814.54474915"
        },
        "2025-07-13": {
            "1. open": "109217.98000000",
            "2. high": "119500.00000000",
            "3. low": "107438.33000000",
            "4. close": "119130.81000000",
            "5. volume": "44820.16714683"
        },
        "2025-07-06": {
            "1. open": "108386.44000000",
            "2. high": "110590.00000000",
            "3. low": "105119.70000000",
            "4. close": "109217.98000000",
            "5. volume": "30715.70186972"
        },
        "2025-06-29": {
            "1. open": "100996.87000000",
            "2. high": "108550.00000000",
            "3. low": "99677.07000000",
            "4. close": "108386.44000000",
            "5. volume": "36350.02141530"
        },
        "2025-06-22": {
            "1. open": "105600.21000000",
            "2. high": "109000.00000000",
            "3. low": "98225.01000000",
            "4. close": "100996.87000000",
            "5. volume": "37046.54064646"
        },
        "2025-06-15": {
            "1. open": "105784.41000000",
            "2. high": "110651.12000000",
            "3. low": "102746.01000000",
            "4. close": "105599.25000000",
            "5. volume": "33773.74445488"
        },
        "2025-06-08": {
            "1. open": "105697.93000000",
            "2. high": "106901.68000000",
            "3. low": "100345.73000000",
            "4. close": "105784.40000000",
            "5. volume": "43254.94612671"
        },
        "2025-06-01": {
            "1. open": "109048.41000000",
            "2. high": "110829.42000000",
            "3. low": "103110.01000000",
            "4. close": "105697.94000000",
            "5. volume": "41887.93534153"
        },
        "2025-05-25": {
            "1. open": "106488.77000000",
            "2. high": "112000.00000000",
            "3. low": "102105.00000000",
            "4. close": "109048.68000000",
            "5. volume": "63739.60248987"
        },
        "2025-05-18": {
            "1. open": "104137.58000000",
            "2. high": "106692.97000000",
            "3. low": "100703.71000000",
            "4. close": "106473.46000000",
            "5. volume": "47786.22752308"
        },
        "2025-05-11": {
            "1. open": "94272.54000000",
            "2. high": "104997.00000000",
            "3. low": "93363.28000000",
            "4. close": "104137.62000000",
            "5. volume": "48531.49762066"
        },
        "2025-05-04": {
            "1. open": "93780.56000000",
            "2. high": "97948.56000000",
            "3. low": "92829.44000000",
            "4. close": "94272.55000000",
            "5. volume": "38795.34144368"
        },
        "2025-04-27": {
            "1. open": "85177.33000000",
            "2. high": "95976.34000000",
            "3. low": "85135.98000000",
            "4. close": "93780.57000000",
            "5. volume": "72630.54385958"
        },
        "2025-04-20": {
            "1. open": "83733.07000000",
            "2. high": "86491.40000000",
            "3. low": "83088.02000000",
            "4. close": "85177.34000000",
            "5. volume": "33200.75934913"
        },
        "2025-04-13": {
            "1. open": "78370.15000000",
            "2. high": "86092.99000000",
            "3. low": "74420.69000000",
            "4. close": "83733.07000000",
            "5. volume": "94925.96440012"
        },
        "2025-04-06": {
            "1. open": "82379.98000000",
            "2. high": "88530.00000000",
            "3. low": "77058.99000000",
            "4. close": "78370.75000000",
            "5. volume": "73012.43716974"
        },
        "2025-03-30": {
            "1. open": "86092.95000000",
            "2. high": "88804.64000000",
            "3. low": "81538.88000000",
            "4. close": "82379.98000000",
            "5. volume": "52750.06691041"
        },
        "2025-03-23": {
            "1. open": "82562.50000000",
            "2. high": "87492.87000000",
            "3. low": "81125.00000000",
            "4. close": "86092.94000000",
            "5. volume": "49872.58095231"
        },
        "2025-03-16": {
            "1. open": "80708.21000000",
            "2. high": "85318.61000000",
            "3. low": "76555.00000000",
            "4. close": "82562.57000000",
            "5. volume": "78844.77700546"
        },
        "2025-03-09": {
            "1. open": "94265.47000000",
            "2. high": "94415.61000000",
            "3. low": "80000.00000000",
            "4. close": "80699.17000000",
            "5. volume": "111752.31067722"
        },
        "2025-03-02": {
            "1. open": "96266.23000000",
            "2. high": "96515.41000000",
            "3. low": "78167.81000000",
            "4. close": "94265.48000000",
            "5. volume": "136996.58684155"
        },
        "2025-02-23": {
            "1. open": "96119.88000000",
            "2. high": "99517.52000000",
            "3. low": "93333.00000000",
            "4. close": "96265.98000000",
            "5. volume": "60338.81665337"
        },
        "2025-02-16": {
            "1. open": "96481.47000000",
            "2. high": "98890.11000000",
            "3. low": "94066.92000000",
            "4. close": "96119.88000000",
            "5. volume": "41540.37686367"
        },
        "2025-02-09": {
            "1. open": "97676.53000000",
            "2. high": "102599.85000000",
            "3. low": "91178.01000000",
            "4. close": "96475.82000000",
            "5. volume": "82537.11655755"
        },
        "2025-02-02": {
            "1. open": "102565.28000000",
            "2. high": "106484.77000000",
            "3. low": "96179.00000000",
            "4. close": "97676.52000000",
            "5. volume": "84670.81424465"
        },
        "2025-01-26": {
            "1. open": "101217.78000000",
            "2. high": "109358.01000000",
            "3. low": "99416.27000000",
            "4. close": "102563.00000000",
            "5. volume": "108450.51477696"
        },
        "2025-01-19": {
            "1. open": "94507.24000000",
            "2. high": "106314.44000000",
            "3. low": "89028.64000000",
            "4. close": "101211.13000000",
            "5. volume": "91894.97309210"
        },
        "2025-01-12": {
            "1. open": "98347.65000000",
            "2. high": "102735.99000000",
            "3. low": "91187.00000000",
            "4. close": "94509.62000000",
            "5. volume": "72954.06869242"
        },
        "2025-01-05": {
            "1. open": "93563.35000000",
            "2. high": "98969.92000000",
            "3. low": "91271.19000000",
            "4. close": "98345.33000000",
            "5. volume": "57545.98596124"
        },
        "2024-12-29": {
            "1. open": "95091.15000000",
            "2. high": "99887.00000000",
            "3. low": "92360.91000000",
            "4. close": "93563.35000000",
            "5. volume": "62799.27799097"
        },
        "2024-12-22": {
            "1. open": "104608.00000000",
            "2. high": "108239.00000000",
            "3. low": "92450.00000000",
            "4. close": "95136.87000000",
            "5. volume": "795431377828.98254395"
        },
        "2024-12-15": {
            "1. open": "100968.00000000",
            "2. high": "104921.00000000",
            "3. low": "94371.10000000",
            "4. close": "104621.00000000",
            "5. volume": "804276038882.03137207"
        },
        "2024-12-08": {
            "1. open": "97183.98000000",
            "2. high": "103484.00000000",
            "3. low": "93618.44000000",
            "4. close": "101215.00000000",
            "5. volume": "850127733010.91015625"
        },
        "2024-12-01": {
            "1. open": "97736.05000000",
            "2. high": "98746.64000000",
            "3. low": "90860.03000000",
            "4. close": "97236.30000000",
            "5. volume": "612461115280.07324219"
        },
        "2024-11-24": {
            "1. open": "89782.53000000",
            "2. high": "99498.52000000",
            "3. low": "89453.11000000",

In [ ]:
ts2.get_weekly("MSFT")
ts2.get_monthly("MSFT")

In [ ]:
url="https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol=MSFT&apikey={api}"
r=requests.get(url)
fd=BeautifulSoup(r.content)
print(fd)

<html><body>{
    "symbol": "MSFT",
    "annualReports": [
        {
            "fiscalDateEnding": "2025-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "193893000000",
            "totalRevenue": "281724000000",
            "costOfRevenue": "87831000000",
            "costofGoodsAndServicesSold": "87831000000",
            "operatingIncome": "128528000000",
            "sellingGeneralAndAdministrative": "7223000000",
            "researchAndDevelopment": "32488000000",
            "operatingExpenses": "65365000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "262000000",
            "interestIncome": "767000000",
            "interestExpense": "2385000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "None",
            "depreciation": "None",
            "depreciationAndAmortization": "34153000000",
            "incomeBeforeTax": "123627000000",
            "incomeTaxExpense": "21795000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "101832000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "126012000000",
            "ebitda": "160165000000",
            "netIncome": "101832000000"
        },
        {
            "fiscalDateEnding": "2024-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "171008000000",
            "totalRevenue": "245122000000",
            "costOfRevenue": "74114000000",
            "costofGoodsAndServicesSold": "74114000000",
            "operatingIncome": "109433000000",
            "sellingGeneralAndAdministrative": "7609000000",
            "researchAndDevelopment": "29510000000",
            "operatingExpenses": "61575000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "222000000",
            "interestIncome": "3157000000",
            "interestExpense": "2935000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "None",
            "depreciation": "None",
            "depreciationAndAmortization": "22287000000",
            "incomeBeforeTax": "107787000000",
            "incomeTaxExpense": "19651000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "88136000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "110722000000",
            "ebitda": "133009000000",
            "netIncome": "88136000000"
        },
        {
            "fiscalDateEnding": "2023-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "146052000000",
            "totalRevenue": "211915000000",
            "costOfRevenue": "65863000000",
            "costofGoodsAndServicesSold": "65863000000",
            "operatingIncome": "88523000000",
            "sellingGeneralAndAdministrative": "7575000000",
            "researchAndDevelopment": "27195000000",
            "operatingExpenses": "57529000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "1026000000",
            "interestIncome": "1041000000",
            "interestExpense": "1968000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "None",
            "depreciation": "None",
            "depreciationAndAmortization": "13861000000",
            "incomeBeforeTax": "89311000000",
            "incomeTaxExpense": "16950000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "72361000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "91279000000",
            "ebitda": "105140000000",
            "netIncome": "72361000000"
        },
        {
            "fiscalDateEnding": "2022-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "135620000000",
            "totalRevenue": "198270000000",
            "costOfRevenue": "62650000000",
            "costofGoodsAndServicesSold": "62650000000",
            "operatingIncome": "83383000000",
            "sellingGeneralAndAdministrative": "5900000000",
            "researchAndDevelopment": "24512000000",
            "operatingExpenses": "52237000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "31000000",
            "interestIncome": "2094000000",
            "interestExpense": "2063000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "333000000",
            "depreciation": "None",
            "depreciationAndAmortization": "14460000000",
            "incomeBeforeTax": "83716000000",
            "incomeTaxExpense": "10978000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "72738000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "85779000000",
            "ebitda": "100239000000",
            "netIncome": "72738000000"
        },
        {
            "fiscalDateEnding": "2021-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "115856000000",
            "totalRevenue": "168088000000",
            "costOfRevenue": "52232000000",
            "costofGoodsAndServicesSold": "52232000000",
            "operatingIncome": "69916000000",
            "sellingGeneralAndAdministrative": "5107000000",
            "researchAndDevelopment": "20716000000",
            "operatingExpenses": "45940000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-215000000",
            "interestIncome": "2131000000",
            "interestExpense": "2346000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1186000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11686000000",
            "incomeBeforeTax": "71102000000",
            "incomeTaxExpense": "9831000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "61271000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "73448000000",
            "ebitda": "85134000000",
            "netIncome": "61271000000"
        },
        {
            "fiscalDateEnding": "2020-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "96937000000",
            "totalRevenue": "143015000000",
            "costOfRevenue": "46078000000",
            "costofGoodsAndServicesSold": "46078000000",
            "operatingIncome": "52959000000",
            "sellingGeneralAndAdministrative": "5111000000",
            "researchAndDevelopment": "19269000000",
            "operatingExpenses": "43978000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-2591000000",
            "interestIncome": "2680000000",
            "interestExpense": "2591000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "77000000",
            "depreciation": "None",
            "depreciationAndAmortization": "12796000000",
            "incomeBeforeTax": "53036000000",
            "incomeTaxExpense": "8755000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "44281000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "55627000000",
            "ebitda": "68423000000",
            "netIncome": "44281000000"
        },
        {
            "fiscalDateEnding": "2019-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "82933000000",
            "totalRevenue": "125843000000",
            "costOfRevenue": "42910000000",
            "costofGoodsAndServicesSold": "42910000000",
            "operatingIncome": "42959000000",
            "sellingGeneralAndAdministrative": "4885000000",
            "researchAndDevelopment": "16876000000",
            "operatingExpenses": "39974000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-2686000000",
            "interestIncome": "812000000",
            "interestExpense": "2686000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "729000000",
            "depreciation": "None",
            "depreciationAndAmortization": "11682000000",
            "incomeBeforeTax": "43688000000",
            "incomeTaxExpense": "4448000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "39240000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "46374000000",
            "ebitda": "58056000000",
            "netIncome": "39240000000"
        },
        {
            "fiscalDateEnding": "2018-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "72007000000",
            "totalRevenue": "110360000000",
            "costOfRevenue": "38353000000",
            "costofGoodsAndServicesSold": "38353000000",
            "operatingIncome": "35058000000",
            "sellingGeneralAndAdministrative": "4754000000",
            "researchAndDevelopment": "14726000000",
            "operatingExpenses": "36949000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-2733000000",
            "interestIncome": "1522000000",
            "interestExpense": "2733000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "1416000000",
            "depreciation": "None",
            "depreciationAndAmortization": "10261000000",
            "incomeBeforeTax": "36474000000",
            "incomeTaxExpense": "19903000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "16571000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "39207000000",
            "ebitda": "49468000000",
            "netIncome": "16571000000"
        },
        {
            "fiscalDateEnding": "2017-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "62310000000",
            "totalRevenue": "96571000000",
            "costOfRevenue": "34261000000",
            "costofGoodsAndServicesSold": "34261000000",
            "operatingIncome": "29025000000",
            "sellingGeneralAndAdministrative": "4481000000",
            "researchAndDevelopment": "13037000000",
            "operatingExpenses": "32979000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-2222000000",
            "interestIncome": "1182000000",
            "interestExpense": "2222000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "823000000",
            "depreciation": "None",
            "depreciationAndAmortization": "8778000000",
            "incomeBeforeTax": "29901000000",
            "incomeTaxExpense": "4412000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "21204000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "32123000000",
            "ebitda": "40901000000",
            "netIncome": "25489000000"
        },
        {
            "fiscalDateEnding": "2016-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "58374000000",
            "totalRevenue": "91154000000",
            "costOfRevenue": "32780000000",
            "costofGoodsAndServicesSold": "32780000000",
            "operatingIncome": "26078000000",
            "sellingGeneralAndAdministrative": "4563000000",
            "researchAndDevelopment": "11988000000",
            "operatingExpenses": "32296000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "-1243000000",
            "interestIncome": "78000000",
            "interestExpense": "1243000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "-431000000",
            "depreciation": "None",
            "depreciationAndAmortization": "6622000000",
            "incomeBeforeTax": "25639000000",
            "incomeTaxExpense": "5100000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "16798000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "26882000000",
            "ebitda": "33504000000",
            "netIncome": "20539000000"
        },
        {
            "fiscalDateEnding": "2015-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "60542000000",
            "totalRevenue": "93580000000",
            "costOfRevenue": "33038000000",
            "costofGoodsAndServicesSold": "33038000000",
            "operatingIncome": "18161000000",
            "sellingGeneralAndAdministrative": "4611000000",
            "researchAndDevelopment": "12046000000",
            "operatingExpenses": "42381000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "781000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "346000000",
            "depreciation": "None",
            "depreciationAndAmortization": "5957000000",
            "incomeBeforeTax": "18507000000",
            "incomeTaxExpense": "6314000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "12193000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "19288000000",
            "ebitda": "25245000000",
            "netIncome": "12193000000"
        },
        {
            "fiscalDateEnding": "2014-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "59755000000",
            "totalRevenue": "86833000000",
            "costOfRevenue": "27078000000",
            "costofGoodsAndServicesSold": "27078000000",
            "operatingIncome": "27759000000",
            "sellingGeneralAndAdministrative": "4677000000",
            "researchAndDevelopment": "11381000000",
            "operatingExpenses": "31869000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "597000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "61000000",
            "depreciation": "None",
            "depreciationAndAmortization": "5212000000",
            "incomeBeforeTax": "27820000000",
            "incomeTaxExpense": "5746000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "22074000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "28417000000",
            "ebitda": "33629000000",
            "netIncome": "22074000000"
        },
        {
            "fiscalDateEnding": "2013-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "57464000000",
            "totalRevenue": "77849000000",
            "costOfRevenue": "20385000000",
            "costofGoodsAndServicesSold": "20385000000",
            "operatingIncome": "26764000000",
            "sellingGeneralAndAdministrative": "5013000000",
            "researchAndDevelopment": "10411000000",
            "operatingExpenses": "30700000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "429000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "288000000",
            "depreciation": "None",
            "depreciationAndAmortization": "3755000000",
            "incomeBeforeTax": "27052000000",
            "incomeTaxExpense": "5189000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "21863000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "27481000000",
            "ebitda": "31236000000",
            "netIncome": "21863000000"
        },
        {
            "fiscalDateEnding": "2012-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "56193000000",
            "totalRevenue": "73723000000",
            "costOfRevenue": "17530000000",
            "costofGoodsAndServicesSold": "17530000000",
            "operatingIncome": "21763000000",
            "sellingGeneralAndAdministrative": "4569000000",
            "researchAndDevelopment": "9811000000",
            "operatingExpenses": "28237000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "380000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "504000000",
            "depreciation": "None",
            "depreciationAndAmortization": "2967000000",
            "incomeBeforeTax": "22267000000",
            "incomeTaxExpense": "5289000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "16978000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "22647000000",
            "ebitda": "25614000000",
            "netIncome": "16978000000"
        },
        {
            "fiscalDateEnding": "2011-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "54366000000",
            "totalRevenue": "69943000000",
            "costOfRevenue": "15577000000",
            "costofGoodsAndServicesSold": "15577000000",
            "operatingIncome": "27161000000",
            "sellingGeneralAndAdministrative": "4222000000",
            "researchAndDevelopment": "9043000000",
            "operatingExpenses": "27205000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "295000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "910000000",
            "depreciation": "None",
            "depreciationAndAmortization": "2766000000",
            "incomeBeforeTax": "28071000000",
            "incomeTaxExpense": "4921000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "23150000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "28366000000",
            "ebitda": "31132000000",
            "netIncome": "23150000000"
        },
        {
            "fiscalDateEnding": "2010-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "50089000000",
            "totalRevenue": "62484000000",
            "costOfRevenue": "12395000000",
            "costofGoodsAndServicesSold": "12395000000",
            "operatingIncome": "24098000000",
            "sellingGeneralAndAdministrative": "4063000000",
            "researchAndDevelopment": "8714000000",
            "operatingExpenses": "25991000000",
            "investmentIncomeNet": "None",
            "netInterestIncome": "None",
            "interestIncome": "None",
            "interestExpense": "151000000",
            "nonInterestIncome": "None",
            "otherNonOperatingIncome": "915000000",
            "depreciation": "None",
            "depreciationAndAmortization": "2673000000",
            "incomeBeforeTax": "25013000000",
            "incomeTaxExpense": "6253000000",
            "interestAndDebtExpense": "None",
            "netIncomeFromContinuingOperations": "18760000000",
            "comprehensiveIncomeNetOfTax": "None",
            "ebit": "25164000000",
            "ebitda": "27837000000",
            "netIncome": "18760000000"
        },
        {
            "fiscalDateEnding": "2009-06-30",
            "reportedCurrency": "USD",
            "grossProfit": "46282000000",
            "totalRevenue": "58437000000",
            "costOfRevenue": "12155000000",
            "costofGoodsAndServicesSold": "12155000000",
            "operatingIncome": "20363000000",

In [ ]:
url="https://www.alphavantage.co/query?function=BBANDS&symbol=MSFT&interval=daily&series_type=close&time_period=10&nbdevup=3&nbdevdn=3&apikey={api}"
r=requests.get(url)
fd=BeautifulSoup(r.content)
print(fd)

<html><body>{
    "Meta Data": {
        "1: Symbol": "MSFT",
        "2: Indicator": "Bollinger Bands (BBANDS)",
        "3: Last Refreshed": "2026-06-04",
        "4: Interval": "daily",
        "5: Time Period": 10,
        "6.1: Deviation multiplier for upper band": 3,
        "6.2: Deviation multiplier for lower band": 3,
        "6.3: MA Type": 0,
        "7: Series Type": "close",
        "8: Time Zone": "US/Eastern Time"
    },
    "Technical Analysis: BBANDS": {
        "2026-06-04": {
            "Real Upper Band": "474.9215",
            "Real Middle Band": "430.0810",
            "Real Lower Band": "385.2405"
        },
        "2026-06-03": {
            "Real Upper Band": "475.0088",
            "Real Middle Band": "429.2908",
            "Real Lower Band": "383.5727"
        },
        "2026-06-02": {
            "Real Upper Band": "475.3576",
            "Real Middle Band": "428.2083",
            "Real Lower Band": "381.0590"
        },
        "2026-06-01": {
            "Real Upper Band": "471.7843",
            "Real Middle Band": "426.3396",
            "Real Lower Band": "380.8949"
        },
        "2026-05-29": {
            "Real Upper Band": "452.3686",
            "Real Middle Band": "422.3881",
            "Real Lower Band": "392.4077"
        },
        "2026-05-28": {
            "Real Upper Band": "432.9398",
            "Real Middle Band": "418.2184",
            "Real Lower Band": "403.4970"
        },
        "2026-05-27": {
            "Real Upper Band": "432.5303",
            "Real Middle Band": "415.9526",
            "Real Lower Band": "399.3750"
        },
        "2026-05-26": {
            "Real Upper Band": "433.7069",
            "Real Middle Band": "415.3743",
            "Real Lower Band": "397.0417"
        },
        "2026-05-22": {
            "Real Upper Band": "433.5430",
            "Real Middle Band": "414.9479",
            "Real Lower Band": "396.3527"
        },
        "2026-05-21": {
            "Real Upper Band": "432.7542",
            "Real Middle Band": "414.5129",
            "Real Lower Band": "396.2716"
        },
        "2026-05-20": {
            "Real Upper Band": "433.0167",
            "Real Middle Band": "414.5898",
            "Real Lower Band": "396.1628"
        },
        "2026-05-19": {
            "Real Upper Band": "431.4692",
            "Real Middle Band": "413.8813",
            "Real Lower Band": "396.2935"
        },
        "2026-05-18": {
            "Real Upper Band": "430.8905",
            "Real Middle Band": "413.2786",
            "Real Lower Band": "395.6668"
        },
        "2026-05-15": {
            "Real Upper Band": "427.2240",
            "Real Middle Band": "412.2888",
            "Real Lower Band": "397.3535"
        },
        "2026-05-14": {
            "Real Upper Band": "423.8335",
            "Real Middle Band": "411.5424",
            "Real Lower Band": "399.2512"
        },
        "2026-05-13": {
            "Real Upper Band": "424.1118",
            "Real Middle Band": "411.3777",
            "Real Lower Band": "398.6437"
        },
        "2026-05-12": {
            "Real Upper Band": "428.0434",
            "Real Middle Band": "413.2986",
            "Real Lower Band": "398.5538"
        },
        "2026-05-11": {
            "Real Upper Band": "433.9389",
            "Real Middle Band": "415.4419",
            "Real Lower Band": "396.9449"
        },
        "2026-05-08": {
            "Real Upper Band": "436.1772",
            "Real Middle Band": "416.6553",
            "Real Lower Band": "397.1334"
        },
        "2026-05-07": {
            "Real Upper Band": "437.9096",
            "Real Middle Band": "417.6032",
            "Real Lower Band": "397.2969"
        },
        "2026-05-06": {
            "Real Upper Band": "437.4084",
            "Real Middle Band": "417.1023",
            "Real Lower Band": "396.7962"
        },
        "2026-05-05": {
            "Real Upper Band": "442.7577",
            "Real Middle Band": "418.9942",
            "Real Lower Band": "395.2307"
        },
        "2026-05-04": {
            "Real Upper Band": "442.6567",
            "Real Middle Band": "420.2694",
            "Real Lower Band": "397.8821"
        },
        "2026-05-01": {
            "Real Upper Band": "442.0876",
            "Real Middle Band": "420.7135",
            "Real Lower Band": "399.3394"
        },
        "2026-04-30": {
            "Real Upper Band": "441.6845",
            "Real Middle Band": "421.5467",
            "Real Lower Band": "401.4089"
        },
        "2026-04-29": {
            "Real Upper Band": "437.0311",
            "Real Middle Band": "422.7920",
            "Real Lower Band": "408.5528"
        },
        "2026-04-28": {
            "Real Upper Band": "439.5355",
            "Real Middle Band": "421.4708",
            "Real Lower Band": "403.4061"
        },
        "2026-04-27": {
            "Real Upper Band": "448.4442",
            "Real Middle Band": "417.8647",
            "Real Lower Band": "387.2851"
        },
        "2026-04-24": {
            "Real Upper Band": "456.4459",
            "Real Middle Band": "413.8284",
            "Real Lower Band": "371.2110"
        },
        "2026-04-23": {
            "Real Upper Band": "464.9740",
            "Real Middle Band": "408.4651",
            "Real Lower Band": "351.9562"
        },
        "2026-04-22": {
            "Real Upper Band": "468.8048",
            "Real Middle Band": "404.2063",
            "Real Lower Band": "339.6079"
        },
        "2026-04-21": {
            "Real Upper Band": "461.7520",
            "Real Middle Band": "398.3600",
            "Real Lower Band": "334.9680"
        },
        "2026-04-20": {
            "Real Upper Band": "455.3969",
            "Real Middle Band": "393.1843",
            "Real Lower Band": "330.9716"
        },
        "2026-04-17": {
            "Real Upper Band": "448.4332",
            "Real Middle Band": "388.6750",
            "Real Lower Band": "328.9169"
        },
        "2026-04-16": {
            "Real Upper Band": "434.6656",
            "Real Middle Band": "383.7527",
            "Real Lower Band": "332.8399"
        },
        "2026-04-15": {
            "Real Upper Band": "416.4518",
            "Real Middle Band": "378.6748",
            "Real Lower Band": "340.8977"
        },
        "2026-04-14": {
            "Real Upper Band": "395.8451",
            "Real Middle Band": "374.5787",
            "Real Lower Band": "353.3122"
        },
        "2026-04-13": {
            "Real Upper Band": "388.7325",
            "Real Middle Band": "371.1710",
            "Real Lower Band": "353.6096"
        },
        "2026-04-10": {
            "Real Upper Band": "386.0164",
            "Real Middle Band": "368.4170",
            "Real Lower Band": "350.8176"
        },
        "2026-04-09": {
            "Real Upper Band": "385.6647",
            "Real Middle Band": "367.9281",
            "Real Lower Band": "350.1915"
        },
        "2026-04-08": {
            "Real Upper Band": "385.1068",
            "Real Middle Band": "367.7255",
            "Real Lower Band": "350.3442"
        },
        "2026-04-07": {
            "Real Upper Band": "384.5257",
            "Real Middle Band": "367.5669",
            "Real Lower Band": "350.6080"
        },
        "2026-04-06": {
            "Real Upper Band": "389.9768",
            "Real Middle Band": "368.6356",
            "Real Lower Band": "347.2943"
        },
        "2026-04-02": {
            "Real Upper Band": "393.5351",
            "Real Middle Band": "369.5326",
            "Real Lower Band": "345.5301"
        },
        "2026-04-01": {
            "Real Upper Band": "400.3859",
            "Real Middle Band": "371.0852",
            "Real Lower Band": "341.7846"
        },
        "2026-03-31": {
            "Real Upper Band": "407.4196",
            "Real Middle Band": "373.3224",
            "Real Lower Band": "339.2251"
        },
        "2026-03-30": {
            "Real Upper Band": "416.7922",
            "Real Middle Band": "376.2400",
            "Real Lower Band": "335.6879"
        },
        "2026-03-27": {
            "Real Upper Band": "421.1968",
            "Real Middle Band": "380.3302",
            "Real Lower Band": "339.4636"
        },
        "2026-03-26": {
            "Real Upper Band": "418.6684",
            "Real Middle Band": "384.1998",
            "Real Lower Band": "349.7312"
        },
        "2026-03-25": {
            "Real Upper Band": "419.4145",
            "Real Middle Band": "387.7810",
            "Real Lower Band": "356.1474"
        },
        "2026-03-24": {
            "Real Upper Band": "420.4468",
            "Real Middle Band": "391.1577",
            "Real Lower Band": "361.8685"
        },
        "2026-03-23": {
            "Real Upper Band": "418.8860",
            "Real Middle Band": "394.4525",
            "Real Lower Band": "370.0190"
        },
        "2026-03-20": {
            "Real Upper Band": "421.1066",
            "Real Middle Band": "397.0878",
            "Real Lower Band": "373.0690"
        },
        "2026-03-19": {
            "Real Upper Band": "419.4902",
            "Real Middle Band": "399.7909",
            "Real Lower Band": "380.0916"
        },
        "2026-03-18": {
            "Real Upper Band": "419.6897",
            "Real Middle Band": "401.9522",
            "Real Lower Band": "384.2148"
        },
        "2026-03-17": {
            "Real Upper Band": "417.2344",
            "Real Middle Band": "403.2903",
            "Real Lower Band": "389.3462"
        },
        "2026-03-16": {
            "Real Upper Band": "416.8710",
            "Real Middle Band": "403.7413",
            "Real Lower Band": "390.6117"
        },
        "2026-03-13": {
            "Real Upper Band": "417.2281",
            "Real Middle Band": "403.6016",
            "Real Lower Band": "389.9752"
        },
        "2026-03-12": {
            "Real Upper Band": "418.7164",
            "Real Middle Band": "403.3212",
            "Real Lower Band": "387.9261"
        },
        "2026-03-11": {
            "Real Upper Band": "418.7220",
            "Real Middle Band": "403.3073",
            "Real Lower Band": "387.8926"
        },
        "2026-03-10": {
            "Real Upper Band": "418.5977",
            "Real Middle Band": "402.8802",
            "Real Lower Band": "387.1627"
        },
        "2026-03-09": {
            "Real Upper Band": "421.5390",
            "Real Middle Band": "401.2078",
            "Real Lower Band": "380.8766"
        },
        "2026-03-06": {
            "Real Upper Band": "422.9539",
            "Real Middle Band": "398.7192",
            "Real Lower Band": "374.4845"
        },
        "2026-03-05": {
            "Real Upper Band": "419.9363",
            "Real Middle Band": "397.5488",
            "Real Lower Band": "375.1612"
        },
        "2026-03-04": {
            "Real Upper Band": "415.1165",
            "Real Middle Band": "396.3294",
            "Real Lower Band": "377.5423"
        },
        "2026-03-03": {
            "Real Upper Band": "412.8168",
            "Real Middle Band": "395.6798",
            "Real Lower Band": "378.5427"
        },
        "2026-03-02": {
            "Real Upper Band": "410.3545",
            "Real Middle Band": "394.8841",
            "Real Lower Band": "379.4137"
        },
        "2026-02-27": {
            "Real Upper Band": "410.9264",
            "Real Middle Band": "395.0692",
            "Real Lower Band": "379.2121"
        },
        "2026-02-26": {
            "Real Upper Band": "411.9708",
            "Real Middle Band": "395.8859",
            "Real Lower Band": "379.8010"
        },
        "2026-02-25": {
            "Real Upper Band": "412.6880",
            "Real Middle Band": "396.0584",
            "Real Lower Band": "379.4288"
        },
        "2026-02-24": {
            "Real Upper Band": "418.7894",
            "Real Middle Band": "397.2287",
            "Real Lower Band": "375.6679"
        },
        "2026-02-23": {
            "Real Upper Band": "422.6281",
            "Real Middle Band": "399.5893",
            "Real Lower Band": "376.5505"
        },
        "2026-02-20": {
            "Real Upper Band": "417.8815",
            "Real Middle Band": "401.1615",
            "Real Lower Band": "384.4415"
        },
        "2026-02-19": {
            "Real Upper Band": "418.9908",
            "Real Middle Band": "400.7168",
            "Real Lower Band": "382.4427"
        },
        "2026-02-18": {
            "Real Upper Band": "422.8659",
            "Real Middle Band": "402.1922",
            "Real Lower Band": "381.5184"
        },
        "2026-02-17": {
            "Real Upper Band": "424.4377",
            "Real Middle Band": "403.3480",
            "Real Lower Band": "382.2584"
        },
        "2026-02-13": {
            "Real Upper Band": "430.8276",
            "Real Middle Band": "405.9872",
            "Real Lower Band": "381.1468"
        },
        "2026-02-12": {
            "Real Upper Band": "439.7909",
            "Real Middle Band": "408.8714",
            "Real Lower Band": "377.9519"
        },
        "2026-02-11": {
            "Real Upper Band": "447.5278",
            "Real Middle Band": "412.0233",
            "Real Lower Band": "376.5188"
        },
        "2026-02-10": {
            "Real Upper Band": "488.5954",
            "Real Middle Band": "419.7150",
            "Real Lower Band": "350.8346"
        },
        "2026-02-09": {
            "Real Upper Band": "512.3409",
            "Real Middle Band": "426.4161",
            "Real Lower Band": "340.4914"
        },
        "2026-02-06": {
            "Real Upper Band": "524.1130",
            "Real Middle Band": "432.0590",
            "Real Lower Band": "340.0049"
        },
        "2026-02-05": {
            "Real Upper Band": "528.2234",
            "Real Middle Band": "438.5112",
            "Real Lower Band": "348.7990"
        },
        "2026-02-04": {
            "Real Upper Band": "521.0556",
            "Real Middle Band": "444.2327",
            "Real Lower Band": "367.4097"
        },
        "2026-02-03": {
            "Real Upper Band": "517.2903",
            "Real Middle Band": "447.2114",
            "Real Lower Band": "377.1324"
        },
        "2026-02-02": {
            "Real Upper Band": "510.5241",
            "Real Middle Band": "451.5232",
            "Real Lower Band": "392.5222"
        },
        "2026-01-30": {
            "Real Upper Band": "506.0108",
            "Real Middle Band": "455.1559",
            "Real Lower Band": "404.3011"
        },
        "2026-01-29": {
            "Real Upper Band": "501.1304",
            "Real Middle Band": "457.7812",
            "Real Lower Band": "414.4321"
        },
        "2026-01-28": {
            "Real Upper Band": "495.0203",
            "Real Middle Band": "460.3577",
            "Real Lower Band": "425.6952"
        },
        "2026-01-27": {
            "Real Upper Band": "489.6333",
            "Real Middle Band": "459.2666",
            "Real Lower Band": "428.8999"
        },
        "2026-01-26": {
            "Real Upper Band": "487.4686",
            "Real Middle Band": "458.9281",
            "Real Lower Band": "430.3876"
        },
        "2026-01-23": {
            "Real Upper Band": "491.9021",
            "Real Middle Band": "459.8241",
            "Real Lower Band": "427.7462"
        },
        "2026-01-22": {
            "Real Upper Band": "496.1930",
            "Real Middle Band": "461.0347",
            "Real Lower Band": "425.8764"
        },
        "2026-01-21": {
            "Real Upper Band": "501.4814",
            "Real Middle Band": "464.2534",
            "Real Lower Band": "427.0253"
        },
        "2026-01-20": {
            "Real Upper Band": "498.8655",
            "Real Middle Band": "467.6781",
            "Real Lower Band": "436.4907"
        },
        "2026-01-16": {
            "Real Upper Band": "496.7773",
            "Real Middle Band": "469.5030",
            "Real Lower Band": "442.2287"
        },
        "2026-01-15": {
            "Real Upper Band": "495.4497",
            "Real Middle Band": "470.8052",
            "Real Lower Band": "446.1606"
        },
        "2026-01-14": {
            "Real Upper Band": "493.7259",
            "Real Middle Band": "473.4892",
            "Real Lower Band": "453.2525"
        },
        "2026-01-13": {
            "Real Upper Band": "491.4608",
            "Real Middle Band": "476.2867",
            "Real Lower Band": "461.1126"
        },
        "2026-01-12": {
            "Real Upper Band": "492.7571",
            "Real Middle Band": "477.9224",
            "Real Lower Band": "463.0877"
        },
        "2026-01-09": {
            "Real Upper Band": "494.9424",
            "Real Middle Band": "478.9707",
            "Real Lower Band": "462.9991"
        },
        "2026-01-08": {
            "Real Upper Band": "496.8094",
            "Real Middle Band": "479.8409",
            "Real Lower Band": "462.8723"
        },
        "2026-01-07": {
            "Real Upper Band": "497.7080",
            "Real Middle Band": "480.7110",
            "Real Lower Band": "463.7139"
        },
        "2026-01-06": {
            "Real Upper Band": "497.9485",
            "Real Middle Band": "480.8553",
            "Real Lower Band": "463.7621"
        },
        "2026-01-05": {
            "Real Upper Band": "498.2334",
            "Real Middle Band": "481.5930",
            "Real Lower Band": "464.9527"
        },
        "2026-01-02": {
            "Real Upper Band": "495.3540",
            "Real Middle Band": "482.7011",
            "Real Lower Band": "470.0482"
        },
        "2025-12-31": {
            "Real Upper Band": "493.0488",
            "Real Middle Band": "483.0177",
            "Real Lower Band": "472.9865"
        },
        "2025-12-30": {
            "Real Upper Band": "495.0497",
            "Real Middle Band": "482.2979",
            "Real Lower Band": "469.5461"
        },
        "2025-12-29": {
            "Real Upper Band": "495.9648",
            "Real Middle Band": "481.0375",
            "Real Lower Band": "466.1103"
        },
        "2025-12-26": {
            "Real Upper Band": "495.0806",
            "Real Middle Band": "480.1843",
            "Real Lower Band": "465.2881"
        },
        "2025-12-24": {
            "Real Upper Band": "493.7481",
            "Real Middle Band": "479.7622",
            "Real Lower Band": "465.7764"
        },
        "2025-12-23": {
            "Real Upper Band": "491.6343",
            "Real Middle Band": "478.8204",
            "Real Lower Band": "466.0065"
        },
        "2025-12-22": {
            "Real Upper Band": "494.8276",
            "Real Middle Band": "479.3351",
            "Real Lower Band": "463.8426"
        },
        "2025-12-19": {
            "Real Upper Band": "497.4753",
            "Real Middle Band": "479.9424",
            "Real Lower Band": "462.4095"
        },
        "2025-12-18": {
            "Real Upper Band": "496.8323",
            "Real Middle Band": "479.6676",
            "Real Lower Band": "462.5030"
        },
        "2025-12-17": {
            "Real Upper Band": "496.3952",
            "Real Middle Band": "479.3550",
            "Real Lower Band": "462.3148"
        },
        "2025-12-16": {
            "Real Upper Band": "496.1591",
            "Real Middle Band": "479.5153",
            "Real Lower Band": "462.8715"
        },
        "2025-12-15": {
            "Real Upper Band": "498.1303",
            "Real Middle Band": "480.8703",
            "Real Lower Band": "463.6102"
        },
        "2025-12-12": {
            "Real Upper Band": "497.4747",
            "Real Middle Band": "482.0570",
            "Real Lower Band": "466.6392"
        },